### PR TITLE
Ignore empty IP addresses and traceroute data

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/140)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
One clarifying question.

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/140#-:-Msk8kWL6gLKEpTp2GsL:b-cn3pyx)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[internal/triggertrace/triggertrace.go, line 103 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/140#-Msk7vBfEAy0DNy2AcNz:-Msk7vBgDgIGM7oXWK4d:b-xf87qp) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8e50dfd6187d5a563567b37a8590cd6583202431/internal/triggertrace/triggertrace.go#L103)):*
> ```Go
> 	destination, err := h.findDestination(sockID)
> 	if err != nil {
> 		log.Printf("context %p: failed to find destination from SockID %+v\n", ctx, *sockID)
> ```

I like this :+1:
___
*[parser/scamper1.go, line 168 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/140#-Msk89FgCuRl12osa4aI:-Msk89FgCuRl12osa4aJ:b-arxio7) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8e50dfd6187d5a563567b37a8590cd6583202431/parser/scamper1.go#L168)):*
> ```Go
> 				// Parse the IP string, to avoid formatting variations.
> 				ip := net.ParseIP(link.Addr)
> 				if ip.String() != "<nil>" && ip.String() != "*" {
> ```

Under what conditions does `ip.String()` return `*`? I'm not sure -- https://go.dev/play/p/YxHvwkdiWNk

If this can be unit tested, all the better.
___
*[tracer/scamper.go, line 145 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/140#-Msk8POH5vuGLIRFX5vD:-Msk8POH5vuGLIRFX5vE:b19po7c) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8e50dfd6187d5a563567b37a8590cd6583202431/tracer/scamper.go#L145)):*
> ```Go
> 	}
> 	if len(data) == 0 {
> 		return nil, fmt.Errorf("context %p: failed to obtain a traceroute (command: %v)", ctx, cmd)
> ```

Not for this PR - but it could be helpful to have metrics for events like this. At one time I hoped we could have a complete accounting of how every event received from tcpinfo passes through traceroute-caller, either "success"fully or with some specific error like this, e.g. "no-data", "command-error", etc.

**Comment by SaiedKazemi** [comment]
___
*[internal/triggertrace/triggertrace.go, line 103 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/140#-Msk7vBfEAy0DNy2AcNz:-MsnxAf95mUWAc_i5v3U:b-xrwev0) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8e50dfd6187d5a563567b37a8590cd6583202431/internal/triggertrace/triggertrace.go#L103)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I like this :+1:
</blockquote></details>

Yup, adding context makes it possible to easily group the lines throughout the logs that are related to the same traceroute.  Super helpful for debugging.

**Comment by SaiedKazemi** [comment]
___
*[parser/scamper1.go, line 168 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/140#-Msk89FgCuRl12osa4aI:-MsnxyFg73XJ_vNtMV3P:bdt6jo1) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8e50dfd6187d5a563567b37a8590cd6583202431/parser/scamper1.go#L168)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Under what conditions does `ip.String()` return `*`? I'm not sure -- https://go.dev/play/p/YxHvwkdiWNk

If this can be unit tested, all the better.
</blockquote></details>

Thank you for pointing this out.  I was too quick to assume `ip.String()` can return `"*"`.  The culprit must be a few lines above `hops[node.Addr] = struct{}{}` which I hadn't noticed because `hops[node.Addr]` has never been `"*"` in my local tests.  I have added a check there and have also added a specific unit test.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 145 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/140#-Msk8POH5vuGLIRFX5vD:-MsnzH1I1sCnRdfgzurG:boznlwi) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8e50dfd6187d5a563567b37a8590cd6583202431/tracer/scamper.go#L145)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Not for this PR - but it could be helpful to have metrics for events like this. At one time I hoped we could have a complete accounting of how every event received from tcpinfo passes through traceroute-caller, either "success"fully or with some specific error like this, e.g. "no-data", "command-error", etc.
</blockquote></details>

I agree.  In fact, I would like to revisit all event metrics traceroute-caller emits if we can prioritize and allocate time for it.

**Review by SaiedKazemi — COMMENTED** [review]
Thank you for your review.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/140#-:-MsnzuOK6bj6SVrq7t5j:bp9kcar)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/140#-:-MsolJQl8Mw5AWEkaYuR:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by SaiedKazemi** [comment]
Thank you.

**Pull request merged**
