### PR TITLE
Restore functionality to traceroutecaller 2 (v0.6.0)

### PR DESCRIPTION
**Pull request by gfr10598**
The makes the necessary changes to remove annotation functionality, and write out just metadata+scamper records.
The parser and schema packages are left in place, but there are no dependencies on them.
This should be deployed all the way to prod after validation.

Testing:
   Manually compared unit tests to v0.6.0
   Passes all unit tests.
   Need to run in sandbox after initial review.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/96)

### CODE REVIEW

**Review by SaiedKazemi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/96)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[connectionlistener/connectionlistener_test.go, line 38 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-MbEKr3U4GkiEl70k5DD:-MbEKr3VB9cZ8EBGGpKu:bc6jslb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/eb400e49e368be35bb5df67ea3ea60442e268a51/connectionlistener/connectionlistener_test.go#L38)):*
> ```Go
> 	ft.ips = append(ft.ips, conn.RemoteIP)
> 	ft.wg.Done()
> 	return "Fake test Result", nil
> ```

nit: "Fake test result" for consistency with other messages we have fixed
___
*[parser/pt.go, line 5 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-MbELNC1Eg4j6goyXU_0:-MbELNC1Eg4j6goyXU_1:bro1ocy) ([raw file](https://github.com/m-lab/traceroute-caller/blob/eb400e49e368be35bb5df67ea3ea60442e268a51/parser/pt.go#L5)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // Much of this file is copied from code in etl/parser/pt.go.  This comment
> // (just below) doesn't really belong here.  Node, ProcessAllNodes, Unique,
> // ParseFirstLine, ParseOneTuple, and Parse are duplicated almost exactly
> // from etl.  However, much of that code is for handling different "legacy"
> // Paris traceroute data, and does not belong here.
> ```
</details>


Per guidelines for "Package comments" (go/go-style/decisions#package-comments), can we move this block to before package declaration and reformat the first sentence?
___
*[parser/pt.go, line 83 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-MbEMb-v8l4DkzfA0mb4:-MbEMb-v8l4DkzfA0mb5:b-a02w6x) ([raw file](https://github.com/m-lab/traceroute-caller/blob/eb400e49e368be35bb5df67ea3ea60442e268a51/parser/pt.go#L83)):*
> ```Go
> }
> 
> // XXX vvvvvvv Largely copy paste from etl/parser/pt.go
> ```

Can the duplicate body of code be placed in a package to avoid copying and having to maintain it in two different files?
___
*[tracer/scamper.go, line 111 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-MbENbx8CMwA9itmP1q4:-MbENbx8CMwA9itmP1q5:b-jq6zht) ([raw file](https://github.com/m-lab/traceroute-caller/blob/eb400e49e368be35bb5df67ea3ea60442e268a51/tracer/scamper.go#L111)):*
> ```
> 	return string(buff.Bytes()), nil
> ```
Can we replace this with the following?
       return buff.String(), nil
___
*[tracer/scamper.go, line 221 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-MbENpTx28lEOneWTGIW:-MbENpTx28lEOneWTGIX:b-d1vjeg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/eb400e49e368be35bb5df67ea3ea60442e268a51/tracer/scamper.go#L221)):*
> ```Go
> 	rtx.PanicOnError(err, "Command %v failed", cmd)
> 	rtx.PanicOnError(ioutil.WriteFile(filename, buff.Bytes(), 0666), "Could not save output to file")
> 	return string(buff.Bytes()), nil
> ```

Same as before: return buff.String(), nil
___
*[tracer/tracer.go, line 61 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-MbENzeR0_AzWu5TibEf:-MbENzeR0_AzWu5TibEg:b-kn2g66) ([raw file](https://github.com/m-lab/traceroute-caller/blob/eb400e49e368be35bb5df67ea3ea60442e268a51/tracer/tracer.go#L61)):*
> ```
> 	hostname string
> ```
The test code sets `hostname` but does not use it.  How is `hostname` which isn't exported used by this package?

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/96)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

**Review by SaiedKazemi — COMMENTED** [review]
Overall looks pretty good.  I just made a few minor comments in the code.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-:-MbEOrkUAfYxgs1ABkHG:bjjw6uw)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/96)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

___
*[parser/pt.go, line 5 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-MbELNC1Eg4j6goyXU_0:-MbH5laz-5wVWqf_1a6a:bdq7ge3) ([raw file](https://github.com/m-lab/traceroute-caller/blob/eb400e49e368be35bb5df67ea3ea60442e268a51/parser/pt.go#L5)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

> ```
> // Much of this file is copied from code in etl/parser/pt.go.  This comment
> // (just below) doesn't really belong here.  Node, ProcessAllNodes, Unique,
> // ParseFirstLine, ParseOneTuple, and Parse are duplicated almost exactly
> // from etl.  However, much of that code is for handling different "legacy"
> // Paris traceroute data, and does not belong here.
> ```

Per guidelines for "Package comments" (go/go-style/decisions#package-comments), can we move this block to before package declaration and reformat the first sentence?
</blockquote></details>

Updated and added notice that the package/file is obsolete and will be deleted soon.
___
*[parser/pt.go, line 83 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-MbEMb-v8l4DkzfA0mb4:-MbH5wll2Ncy_kn4FB79:b-ywsxxl) ([raw file](https://github.com/m-lab/traceroute-caller/blob/eb400e49e368be35bb5df67ea3ea60442e268a51/parser/pt.go#L83)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Can the duplicate body of code be placed in a package to avoid copying and having to maintain it in two different files?
</blockquote></details>

I could, but we will delete it instead in the next PR.
___
*[tracer/scamper.go, line 111 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/96#-MbENbx8CMwA9itmP1q4:-MbH6duh9bGx5T8Ii2ki:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/eb400e49e368be35bb5df67ea3ea60442e268a51/tracer/scamper.go#L111)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

> ```
> 	return string(buff.Bytes()), nil
> ```
Can we replace this with the following?
       return buff.String(), nil

</blockquote></details>

Done.

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/96)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
