### PR TITLE
Add time columns to output and make some code improvements

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit adds probe transmit and reply receive times to
the output it generates.  This commit also makes some code
improvements.

The changes were tested locally using .jsonl archives from GCS.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/149)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - the duplicate example text worries me. Doesn't have to be blocking.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/149#-:-N6wgNB-BNJoTSREmoNn:b-v1cbx3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`cmd/trex/main.go` line 213 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/149#-N6wcw4IEBAaMis9M4Iw:-N6wcw4IEBAaMis9M4Ix:btxphbf) ([raw file](https://github.com/m-lab/traceroute-caller/blob/5470e26add9bf0a578edb23191bc8bced90834a0/cmd/trex/main.go#L213)):*
> ```Go
> 
> 	// Create a buffer for verbose output.
> 	vbuf := ""
> ```

Did you also consider `fmt.Fprintf` and `bytes.Buffer` for this case?
___
*[`cmd/trex/main.go` line 422 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/149#-N6wfbe7-95GdHIQ4x-q:-N6wfbe7-95GdHIQ4x-r:be9y7u1) ([raw file](https://github.com/m-lab/traceroute-caller/blob/5470e26add9bf0a578edb23191bc8bced90834a0/cmd/trex/main.go#L422)):*
> ```Go
> func printExamples() {
> 	fmt.Printf(`Examples:
> # Extract and print a single-path traceroute (if it exists) from a traceroute file
> ```

Is there a way to include this example text only once either here or in the README?

**Comment by SaiedKazemi** [comment]
@stephen-soltesz Thank you for your review.  I've made edits based on your and Maxime's feedback.  PTAL.

**Comment by SaiedKazemi** [comment]
*[`cmd/trex/main.go` line 213 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/149#-N6wcw4IEBAaMis9M4Iw:-N6yH9Mm9vZL3OOSqy0S:bihzqvh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/5470e26add9bf0a578edb23191bc8bced90834a0/cmd/trex/main.go#L213)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Did you also consider `fmt.Fprintf` and `bytes.Buffer` for this case?
</blockquote></details>

I left it as is for now unless you think it's important to change it.

**Comment by SaiedKazemi** [comment]
PTAL.

**Review by SaiedKazemi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/149)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/trex/main.go` line 422 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/149#-N6wfbe7-95GdHIQ4x-q:-N6yH7pU1oArzVWsCS4M:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/5470e26add9bf0a578edb23191bc8bced90834a0/cmd/trex/main.go#L422)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is there a way to include this example text only once either here or in the README?
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/149#-:-N6yHUw1CineY-HyCri4:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`cmd/trex/main.go` line 213 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/149#-N6wcw4IEBAaMis9M4Iw:-N6yHRIw3-tNpAqECIoS:bqrbpd) ([raw file](https://github.com/m-lab/traceroute-caller/blob/5470e26add9bf0a578edb23191bc8bced90834a0/cmd/trex/main.go#L213)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I left it as is for now unless you think it's important to change it.
</blockquote></details>

You don't have to do that. I just wanted to be sure it was considered :)

**Review by stephen-soltesz — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/149)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Pull request merged**
