### PR TITLE
Fix deadlock bug in ipcache

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/43)

### CODE REVIEW

**Review by gfr10598 — APPROVED** [review]
:lgtm:  but some suggestions for further improvement:

I like the pattern that you use for populating the cache entry, but I think it could be clearer and safer with a few modifications...

The fact that Trace() and CreateCacheTrace both write files is confusing.  It seems like it would be much clearer if there was a function that generates a trace, and a function that creates a file.

If that were the case, then you could replace the channel with a sync.Once, and have a GetData(ip string) that uses once.Do() to create the trace in the cache entry.  The you would get the cache entry, call GetData() on the cache entry, then call the function to create the file.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/43#-:-LvDCNtK18h8tDZVmTZW:b-vy48ua)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @pboothe)

___
*[ipcache/ipcache.go, line 58 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/43#-LvD9VJ72tbf7OUtmhmJ:-LvD9VJ72tbf7OUtmhmK:b7m3alh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/66e69a038679f6e1eddbeb136b7022bc280a8e48/ipcache/ipcache.go#L58)):*
> ```Go
> 
> // Trace performs a trace and adds it to the cache.
> func (rc *RecentIPCache) Trace(conn connection.Connection) string {
> ```

IIUC, Trace and CreateCacheTest both create a file on the filesystem?  If so, that needs to be spelled out in the doc comment for this function, and probably reflected in the name.
The fact that it returns a string makes it easy to believe it has no side effects (aside from cache contents).
___
*[ipcache/ipcache_test.go, line 48 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/43#-LvDC8257_nL0kLLbBmN:-LvDC8257_nL0kLLbBmO:b-2he4qg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/66e69a038679f6e1eddbeb136b7022bc280a8e48/ipcache/ipcache_test.go#L48)):*
> ```Go
> 		RemoteIP:   "1.1.1.5",
> 		RemotePort: 5034,
> 		LocalIP:    "1.1.1.7",
> ```

Feels like LocalIP should be the same here and above, for consistency with expected use.

**Review by gfr10598 — APPROVED** [review]
Basic idea for concurrent test:

Inject a fake Tracer that waits random O(10*microseconds), then returns appropriate string.
Create a waitgroup and .Add(10000)
Spew 10000 go routines each of which:
   1. delays a random number of nanoseconds O(10 microseconds)
   2. calls something like cache.GetDataFor(fmt.Sprint(i % 1000)
   3. calls wg.Done()
wg.Wait()
Then check that a suitably small period of time elapsed, and that all the cache entries
exist and have expected values.

Then run it with -race.
A related example: etl-gardener/tracker/tracker_race_test.go

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/43#-:-LvDDbeCDYBSHYqXLLrM:bpydsw6)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @pboothe)

**Comment by pboothe** [comment]
I agree with your suggestions, let's file them as issues.  I also agree that that the tracer API is a little funny.

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/traceroute-caller/issues/38

**Pull request merged**
