### PR TITLE
Make golangci-lint pass.

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/99)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
Notice that this PR should be merged after PR #97.

**Review by gfr10598 — COMMENTED** [review]
I rebased on master (after #97)
git rebase -i master  // then edit out redundant commits
git diff origin/saied-remove-schema 
git push -f

> Reviewed 2 of 7 files at r1, 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/99#-:-MbcmKkR9SEfKtviCZDs:bsb8b6z)* status: 0 of 1 approvals obtained

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/99)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[tracer/scamper.go, line 191 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/99#-Mbcn7Nq-rH-nRsfAIpQ:-Mbcn7NrAdOY7XUsvUhw:by88vbp) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fc4d4391f7b32b10b0c365df928603114c9010af/tracer/scamper.go#L191)):*
> ```Go
> 	for _, c := range connections {
> 		log.Printf("PT start: %s %d", c.RemoteIP, c.RemotePort)
> 		go func(c connection.Connection) {
> ```

Hmm - I'm guessing that the previous code was actually buggy - race with value of c changing and goroutine capturing it.
___
*[tracer/scamper_test.go, line 385 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/99#-MbcnZyzEwfnWEC5qzZQ:-MbcnZyzEwfnWEC5qzZR:b7cln16) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ef61483ad2f1458e4f3bcc21d68fb8d4c9cbc21e/tracer/scamper_test.go#L385)):*
> ```Go
> }
> 
> //lint:ignore U1000 This performs a compile time check.
> ```

It is unfortunate to remove these, as they perform a compile time check.  If necessary, we can invoke this from an init() function in the test file to avoid warnings.  I guess this linter doesn't have any way to ignore specific lines/warnings?

**Review by gfr10598 — APPROVED** [review]
Just one suggestion.  I'll try to remember to add metrics (soon) in most of the places you are currently ignoring return values.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/99#-:-MbcnxrT48yHUPyq2jcI:bf7mcah)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 191 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/99#-Mbcn7Nq-rH-nRsfAIpQ:-MbcoPwI80G8e2g1H_T5:bu78uzd) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fc4d4391f7b32b10b0c365df928603114c9010af/tracer/scamper.go#L191)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Hmm - I'm guessing that the previous code was actually buggy - race with value of c changing and goroutine capturing it.
</blockquote></details>

Huh :)

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper_test.go, line 385 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/99#-MbcnZyzEwfnWEC5qzZQ:-MbcoiR210O3iP52-xYd:bx98vfb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ef61483ad2f1458e4f3bcc21d68fb8d4c9cbc21e/tracer/scamper_test.go#L385)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

It is unfortunate to remove these, as they perform a compile time check.  If necessary, we can invoke this from an init() function in the test file to avoid warnings.  I guess this linter doesn't have any way to ignore specific lines/warnings?
</blockquote></details>

Since `assertScamperDaemonIsTracer()` isn't used and can be deleted, it is OK to delete the comment lines above it.

**Pull request merged**
