### PR TITLE
Add json output format

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This is a breaking change. This change adds several new flags, downstream of `-output.format=json`. The goal is to support autoloadable output from traceroute-caller. This change only adds support for "regular" traceroutes in autoloadable, json format. The missing feature needed to support autoloadable mda traces is tracked here https://github.com/m-lab/traceroute-caller/issues/169 .

This change expands support for the scamper2 format to support JSON output. With this, additional configurable options are necessary to make the scamper2 as rich and reliable as possible to complement scamper1 deployments.

This change includes modified flags:
* `-output.format` (new) - specifies either json or jsonl formats. mda json is not supported.
* `-scamper.waitprobe`  (was `-scamper.tracelb-W`) - applies the waitprobe flag to mda and regular traceroutes
* `-scamper.ptr` (was `-scamper.tracelb-ptr`) - applies the ptr flag to mda and regular traceroutes

This change includes a new command
* `cmd/generate-schemas` - for autoloadable deployments, this generates the supported output schemas for scamper2 and hopannotation1 datatypes.

Because of the traceroute-caller object model, the relationship between "parser" and "datatype" requires recording the desired output format and propagating that 

Each datatype struct now supports a single Marshal method:
* `Marshal` produces either a JSON or JSONL object depending on the `format` parameter.

This change renames the `hopannotation.HopAnnotation1` type to `hopannotation.HopAnnotation2` to mirror the common usage on the rest of the M-Lab platform and the scamper1 data.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/168)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Awesome, thanks!

Can you add a sample of the `scamper2` JSON output, please?

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-:-O8hCDI15ZMWbVY7URAL:b7fa26a)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`docker-compose.yaml` line 81 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O8hEJ_5BJCCW1HBAlmZ:-O8hEJ_6053ES2q8PZko:blnf4wz) ([raw file](https://github.com/m-lab/traceroute-caller/blob/28b93f3a784f2d46aa33969ff1860a503a790f84/docker-compose.yaml#L81)):*
> ```YAML
> 
>   trc-scamper2:
>     #profiles:
> ```

Is this intended?
___
*[`cmd/generate-schemas/main.go` line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O8hEQTJDgB3-FcKEjBl:-O8hEQTJDgB3-FcKEjBm:bl60c78) ([raw file](https://github.com/m-lab/traceroute-caller/blob/28b93f3a784f2d46aa33969ff1860a503a790f84/cmd/generate-schemas/main.go#L1)):*
> ```Go
> package main
> ```

We should probably standardize some of these prefixes/functionality in [m-lab/go](https://github.com/m-lab/go). Not a blocker for this PR, though.
___
*[`parser/scamper1.go` line 238 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O8hFH1VEwGByAcZQGh2:-O8hFH1VEwGByAcZQGh3:b-1gqhd5) ([raw file](https://github.com/m-lab/traceroute-caller/blob/28b93f3a784f2d46aa33969ff1860a503a790f84/parser/scamper1.go#L238)):*
> ```Go
> }
> 
> // MarshalAsJSON encodes the scamper object as autoloadable JSON.
> ```

`nit`: for consistency, I feel like both should be `MarshalX` or `MarshalAsX`.
___
*[`tracer/scamper.go` line 173 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O8hFhgX1GUlDNZ3tw5H:-O8hFhgX1GUlDNZ3tw5I:blnf4wz) ([raw file](https://github.com/m-lab/traceroute-caller/blob/28b93f3a784f2d46aa33969ff1860a503a790f84/tracer/scamper.go#L173)):*
> ```Go
> 	timeout := time.Until(deadline)
> 
> 	fmt.Println(cmd)
> ```

Is this intended?

**Review by stephen-soltesz — COMMENTED** [review]
Thank you, I've added a sample file to `parser/testdata/scamper2/valid-simple-json` as part of new tests.

This change is pretty big. If you'd prefer I break it up, I can do that.

PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-:-O9H7FIR5-B6H6wuGzZN:b-kixrbt)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`docker-compose.yaml` line 81 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O8hEJ_5BJCCW1HBAlmZ:-O8r7OBn2DjrlZLVQcbf:b-nncm68) ([raw file](https://github.com/m-lab/traceroute-caller/blob/28b93f3a784f2d46aa33969ff1860a503a790f84/docker-compose.yaml#L81)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Is this intended?
</blockquote></details>

Reverted. This was intended for local testing.
___
*[`cmd/generate-schemas/main.go` line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O8hEQTJDgB3-FcKEjBl:-O9H5vms7TpUWRnoiGjj:buiw64g) ([raw file](https://github.com/m-lab/traceroute-caller/blob/28b93f3a784f2d46aa33969ff1860a503a790f84/cmd/generate-schemas/main.go#L1)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

We should probably standardize some of these prefixes/functionality in [m-lab/go](https://github.com/m-lab/go). Not a blocker for this PR, though.
</blockquote></details>

That's a great idea. The pattern in the generate-schema commands is basically identical.
___
*[`parser/scamper1.go` line 238 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O8hFH1VEwGByAcZQGh2:-O9H6HAcBg5zL0_rnvA-:bhmlmeq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/28b93f3a784f2d46aa33969ff1860a503a790f84/parser/scamper1.go#L238)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

`nit`: for consistency, I feel like both should be `MarshalX` or `MarshalAsX`.
</blockquote></details>

I've changed both to `MarshalAsX` since `MarshalJSON` is reserved by the `json` package. I wanted to preserve the original name here just for backward compatibility but this PR changes multiple other interfaces.
___
*[`tracer/scamper.go` line 173 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O8hFhgX1GUlDNZ3tw5H:-O9M-qrf5evACL5iwPl8:bss4a2b) ([raw file](https://github.com/m-lab/traceroute-caller/blob/28b93f3a784f2d46aa33969ff1860a503a790f84/tracer/scamper.go#L173)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Is this intended?
</blockquote></details>

Removed.

**Review by stephen-soltesz — COMMENTED** [review]
This version is running in mlab-sandbox autonode currently and uploading values to gcs

* https://github.com/m-lab/autonode/pull/20
* https://console.cloud.google.com/storage/browser/archive-mlab-sandbox/autoload/v2/mlab/ndt/scamper2/2024/10/16?project=mlab-sandbox

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-:-O9M1eRl0kUNVKTlvJKk:b-euy33b)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

**Review by cristinaleonr — COMMENTED** [review]
Thank you. It helps that I'd already reviewed some of it :sweat_smile:.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-:-O9M3RDfDUfHHogDNY4q:bkw6sfq)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`go.mod` line 3 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O9M27qs8g5tv1BuSVOZ:-O9M27qs8g5tv1BuSVO_:b-9r213h) ([raw file](https://github.com/m-lab/traceroute-caller/blob/c4f61ed72c7c676f2bfa4667a5d10a6eb2416d5e/go.mod#L3)):*
> ```XML
> module github.com/m-lab/traceroute-caller
> 
> go 1.20
> ```

Why are we going back in versions?
___
*[`hopannotation/hopannotation.go` line 72 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O9M2gj52142ff_OTul1:-O9M2gj52142ff_OTul2:b-et8s33) ([raw file](https://github.com/m-lab/traceroute-caller/blob/c4f61ed72c7c676f2bfa4667a5d10a6eb2416d5e/hopannotation/hopannotation.go#L72)):*
> ```Go
> 
> // HopAnnotation2 is the datatype that is written to the hop annotation file.
> type HopAnnotation2 struct {
> ```

IIUC, this is just for compatibility with `scamper2`? The schema is the same as `HopAnnotation1`, right?

**Review by stephen-soltesz — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-:-O9M81h43OUMNCHDyFPf:b-9755fn)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`go.mod` line 3 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O9M27qs8g5tv1BuSVOZ:-O9M7lp54G0nTXwUvGof:bkj11cz) ([raw file](https://github.com/m-lab/traceroute-caller/blob/c4f61ed72c7c676f2bfa4667a5d10a6eb2416d5e/go.mod#L3)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Why are we going back in versions?
</blockquote></details>

I'm not sure why we went up in versions and (I don't remember now) I think there were some build errors related to the version in travis and we don't seem to need it at 1.21.
___
*[`hopannotation/hopannotation.go` line 72 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-O9M2gj52142ff_OTul1:-O9M6pYCEolWaTHhwPKX:bfosd2g) ([raw file](https://github.com/m-lab/traceroute-caller/blob/c4f61ed72c7c676f2bfa4667a5d10a6eb2416d5e/hopannotation/hopannotation.go#L72)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

IIUC, this is just for compatibility with `scamper2`? The schema is the same as `HopAnnotation1`, right?
</blockquote></details>

This is a long deferred update from https://github.com/m-lab/etl/blob/main/parser/hopannotation2.go#L61 & https://github.com/m-lab/etl/pull/1109/files

By convention we're generating hopannotation2 on the platform already. Rather than cause some confusion here, I'm taking this opportunity to rename it to be consistent with the platform and existing pipeline.

**Review by cristinaleonr — APPROVED** [review]
Great, thanks! Will be cool to see it in BQ :smiley:.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/168#-:-O9M8P_E93ZG9Q6X0ood:bv6k2fm)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Pull request merged**
