### PR TITLE
Add tcpinfo watcher

### PR DESCRIPTION
**Pull request by pboothe**
Watch for connections found by tcp-info.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/31)

### CODE REVIEW

**Comment by pboothe** [comment]
Fixes #31

**Comment by pboothe** [comment]
Depends on https://github.com/m-lab/tcp-info/pull/107

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/31)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[connection/connection.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/31#-LricVCc4bmKhi8ZF--k:-LricVCc4bmKhi8ZF--l:b-fqe5h) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ff5f0e0f2b3c6f093742ae933e27698cf5e2f633/connection/connection.go#L33)):*
> ```Go
> func FromSockID(sockid inetdiag.SockID) Connection {
> 	return Connection{
> 		RemoteIP:   sockid.SrcIP,
> ```

RemoteIP should be sockid.DstIP

**Review by yachang — COMMENTED** [review]
LGTM overall.

Make sure you update the unittest with new src/dest IP setting.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/31#-:-Lrj1gKUChE7cEMcJwsT:b-y5cjzc)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/31)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[connection/connection.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/31#-LricVCc4bmKhi8ZF--k:-LrkIExw59D5C1sRIz4i:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ff5f0e0f2b3c6f093742ae933e27698cf5e2f633/connection/connection.go#L33)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

RemoteIP should be sockid.DstIP
</blockquote></details>

Done.

**Comment by pboothe** [comment]
Ya approved of my update. Merging.

**Pull request merged**
