### PR TITLE
Remove TR3 schema and all related code.

### PR DESCRIPTION
**Pull request by gfr10598**
TODO: rebase after merging #96 

This just rips out code that we do not need for 2.1.  Rather than deleting everything, _**it modifies a bit of the code that decodes**_ the scamper output.  Not clear if this will be useful, or if we will rewrite it later.

Also adds comments about the existing code and changes we should consider.  Some use // XXX and we might want to address them sooner rather than later, or change them to // TODO, or create issues.  Feedback appreciated.

Note that this removes a LOT of dependencies from go.sum.

Testing:
   adapt unit tests to work with modified hop parser
   unit tests pass
   100% test coverage
   docker build succeeds

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/97)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 19 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJGtSi0C_hZ_NVtupy:-MbJGtSi0C_hZ_NVtupz:bpyklkm) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L19)):*
> ```Go
> // InitParserVersion initializes the gParserVersion variable for use by all parsers.
> func InitParserVersion() string {
> 	release, ok := os.LookupEnv("RELEASE_TAG")
> ```

I don't think gParserVersion and InitParserVersion() are needed.  Can we delete them?

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 93 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJHppsBzGLmM7FmE4F:-MbJHppsBzGLmM7FmE4G:biuirwx) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L93)):*
> ```Go
> 
> // Metadata contains the UUID and other metadata provided by the traceroute-caller code.
> type Metadata struct {
> ```

Metadata is also defined in tracer/tracer.go and there's a comment there saying "// TODO: move this struct to ETL parser.".

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 104 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJIAjR0Z-38QzL8E1F:-MbJIAjR0Z-38QzL8E1G:b-7g7747) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L104)):*
> ```Go
> 	Type      string  `json:"type"`      // "cycle-start"
> 	ListName  string  `json:"list_name"` // e.g. "/tmp/scamperctrl:58"
> 	ID        float64 `json:"id"`        // XXX Integer?
> ```

Let's convert this and other integer fields that are defined as float64 to int64.

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 186 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJJ7EM4ZNRD-Gs0nk-:-MbJJ7EM4ZNRD-Gs0nk0:b7hwyos) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L186)):*
> ```
> // Are these necessary, or should we ignore errors in cycleStart/Stop?
> ```
We can leave the extra error checking as is while we're transitioning to the new implementation.  Once we have confidence in the new code, we can delete them.

**Comment by SaiedKazemi** [comment]
___
*[parser/json_test.go, line 27 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJJXnO19kb0n1e3qIU:-MbJJXnO19kb0n1e3qIV:b-csfply) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json_test.go#L27)):*
> ```Go
> 		t.Errorf("Error in InitParserVersion")
> 	}
> }
> ```

We should delete TestInitParserVersion() when we delete InitParserVersion().

**Comment by SaiedKazemi** [comment]
___
*[parser/json_test.go, line 29 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJKBPX3MqXOu4TlYz_:-MbJKBPX3MqXOu4TlYza:b-uxnnvp) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json_test.go#L29)):*
> ```Go
> }
> 
> func TestInitParserVersionCommit(t *testing.T) {
> ```

We should also delete TestInitParserVersionCommit().

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 177 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJKkbiBftLsr71KDCb:-MbJKkbiBftLsr71KDCc:b6vd76i) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L177)):*
> ```Go
> 
> // ExtractTraceLB extracts the traceLB line from scamper JSONL
> func ExtractTraceLB(data []byte) (*TracelbLine, error) {
> ```

Is this exported function used anywhere (other than for testing)?

**Comment by SaiedKazemi** [comment]
Per our offline chat, a lot of additional code can be removed when we switch to a better JSON paster like buger/jsonparser.

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 148 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbI6PEa7o8pziRYTCpq:-MbI6PEa7o8pziRYTCpr:b-2hh8rr) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L148)):*
> ```Go
> // ParseJSONL code in etl/parser/pt.go
> 
> // ExtractHops parses tracelb and extract all hop addresses.
> ```

nit: s/extract/extracts/

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/97)* status: 0 of 1 approvals obtained (waiting on @gfr10598)

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/97)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[parser/json.go, line 19 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJGtSi0C_hZ_NVtupy:-MbaoXXR2FxuVuvzhGTs:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L19)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I don't think gParserVersion and InitParserVersion() are needed.  Can we delete them?
</blockquote></details>

Done.
___
*[parser/json.go, line 93 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJHppsBzGLmM7FmE4F:-MbaomIb0K3la7BQ7tsm:b-3se1r5) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L93)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Metadata is also defined in tracer/tracer.go and there's a comment there saying "// TODO: move this struct to ETL parser.".
</blockquote></details>

Turns out this is dead code now.  Removed it.
___
*[parser/json.go, line 104 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJIAjR0Z-38QzL8E1F:-MbaottU1f4IU-hvggWe:b9or6ve) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L104)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Let's convert this and other integer fields that are defined as float64 to int64.
</blockquote></details>

I'll make that a TODO, but don't want to change functional code in this PR.
___
*[parser/json.go, line 177 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJKkbiBftLsr71KDCb:-MbaqLaAB9SUwji5ITon:b-zhke5n) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L177)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Is this exported function used anywhere (other than for testing)?
</blockquote></details>

Not yet, but if we don't move to buger/jsonparser, we will want this for processing the hop annotations in the near future.  I'll add a comment.
___
*[parser/json.go, line 186 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJJ7EM4ZNRD-Gs0nk-:-Mbaqs9c2N44_9lzDNSc:b-x81clk) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json.go#L186)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

> ```
> // Are these necessary, or should we ignore errors in cycleStart/Stop?
> ```
We can leave the extra error checking as is while we're transitioning to the new implementation.  Once we have confidence in the new code, we can delete them.
</blockquote></details>

I'm updating the comment to a TODO.
___
*[parser/json_test.go, line 27 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJJXnO19kb0n1e3qIU:-Mbaqx9b3E1CyVeWZi7C:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json_test.go#L27)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

We should delete TestInitParserVersion() when we delete InitParserVersion().
</blockquote></details>

Done.
___
*[parser/json_test.go, line 29 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-MbJKBPX3MqXOu4TlYz_:-Mbaqxq_7mByDV0SrSu-:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0d0d657e387dbda272d827fca7704de8d65c10c4/parser/json_test.go#L29)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

We should also delete TestInitParserVersionCommit().
</blockquote></details>

Done.

**Review by gfr10598 — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-:-MbasMMoA9Q1s1u-xGUQ:bb71pro)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

**Review by SaiedKazemi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/97#-:-MbbN9ng9CuJS0zb6wnE:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
