### PR TITLE
100% test coverage

### PR DESCRIPTION
**Pull request by pboothe**
Every line of code is now exercised by a unit test.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/12)

### CODE REVIEW

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/12)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[connection/connection.go, line 22 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-LcXQdgP32EGy4PTeTZl:-LcXQdgP32EGy4PTeTZm:bexiig0) ([raw file](https://github.com/m-lab/traceroute-caller/blob/cd33991d62ac104ebb266bc705e8c2a227a1a3cd/connection/connection.go#L22)):*
> ```Go
> 	// cookie is a hexdecimal string
> 	result, err := strconv.ParseUint(c.Cookie, 16, 64)
> 	log.Println("GOT:", result, err)
> ```

A little bit too much to log this out?

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/12)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[connectionwatcher/connectionwatcher.go, line 24 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-LcXQz1A-vBcAHlfsMDv:-LcXQz1BByj1M-P9w-9h:b-k32xpy) ([raw file](https://github.com/m-lab/traceroute-caller/blob/cd33991d62ac104ebb266bc705e8c2a227a1a3cd/connectionwatcher/connectionwatcher.go#L24)):*
> ```
> "-ss-binary"
> ```
 should be "ss-binary"

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/12)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[ipcache/ipcache.go, line 16 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-LcXWs6-4Uo3HIc-FQMq:-LcXWs6-4Uo3HIc-FQMr:b-i2pnbn) ([raw file](https://github.com/m-lab/traceroute-caller/blob/cd33991d62ac104ebb266bc705e8c2a227a1a3cd/ipcache/ipcache.go#L16)):*
> ```Go
> 
> 	// Do not traceroute to an IP more than once in this many seconds
> 	IPCacheUpdateFrequency = flag.Duration("IPCacheUpdateFrequency", 1*time.Second, "We run the cache eviction loop with this frequency")
> ```

This will increase the amount of test significantly. I would prefer to keep the 120 seconds eviction loop.

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/12)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[ipcache/ipcache.go, line 15 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-LcXXK5dAQJ8YjZl7CoZ:-LcXXK5dAQJ8YjZl7Co_:bbfjbc) ([raw file](https://github.com/m-lab/traceroute-caller/blob/cd33991d62ac104ebb266bc705e8c2a227a1a3cd/ipcache/ipcache.go#L15)):*
> ```Go
> 	IPCacheTimeout = flag.Duration("IPCacheTimeout", 120*time.Second, "Timeout duration in seconds for IPCache")
> 
> 	// Do not traceroute to an IP more than once in this many seconds
> ```

update this doc

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/12)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[scamper/scamper_test.go, line 56 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-LcX_e_SD4SCX17-Yt1V:-LcX_e_TABbQSgeA4Mlz:b6d4o2p) ([raw file](https://github.com/m-lab/traceroute-caller/blob/cd33991d62ac104ebb266bc705e8c2a227a1a3cd/scamper/scamper_test.go#L56)):*
> ```Go
> }
> 
> func TestExistingFileStopsDaemonCreation(t *testing.T) {
> ```

Add doc for the test, like the expected results, and reason for crash

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/12)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[connection/connection.go, line 22 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-LcXQdgP32EGy4PTeTZl:-LcXWqzf6hTIz6SDLkRU:b7h5qz1) ([raw file](https://github.com/m-lab/traceroute-caller/blob/cd33991d62ac104ebb266bc705e8c2a227a1a3cd/connection/connection.go#L22)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

A little bit too much to log this out?
</blockquote></details>

Oops!  This is debugging output that I accidentally left in.  Deleting.
___
*[connectionwatcher/connectionwatcher.go, line 24 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-LcXQz1A-vBcAHlfsMDv:-LcXX1JY83NKMeYsIdqT:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/cd33991d62ac104ebb266bc705e8c2a227a1a3cd/connectionwatcher/connectionwatcher.go#L24)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

> ```
> "-ss-binary"
> ```
 should be "ss-binary"
</blockquote></details>

Done.
___
*[ipcache/ipcache.go, line 15 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-LcXXK5dAQJ8YjZl7CoZ:-LcXay_E6o-_UfKC3HRB:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/cd33991d62ac104ebb266bc705e8c2a227a1a3cd/ipcache/ipcache.go#L15)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

update this doc
</blockquote></details>

Done.
___
*[scamper/scamper_test.go, line 56 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-LcX_e_SD4SCX17-Yt1V:-LcXbc1j4HW0ahuWKfGC:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/cd33991d62ac104ebb266bc705e8c2a227a1a3cd/scamper/scamper_test.go#L56)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add doc for the test, like the expected results, and reason for crash 
</blockquote></details>

Done.

**Comment by pboothe** [comment]
PTAL  Code is stable.

**Review by yachang — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-:-LcY76nWB9GBayj5PIMa:bg7igkv)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

**Review by yachang — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/12#-:-LcY79I93HRouNu6U1uI:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @yachang)

**Pull request merged**
