### PR TITLE
add timeout handling

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/51)

### CODE REVIEW

**Review by pboothe — CHANGES_REQUESTED** [review]
The error should be saved in the cache, and the system that reads cache entries should check whether the error is non-nil before trying to load the cached results.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-:-LvQvE4m5anaI7GDn6KD:b-r8dcva)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[scamper/scamper.go, line 233 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvQunmA9TJdZVl0Ykmk:-LvQunmBCTqywsqu-Tvs:b-qfgljq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/6ff41ed4d5158ecd5e9163db43137910ded3c7ad/scamper/scamper.go#L233)):*
> ```Go
> 			log.Println("TimeOut for Trace: ", cmd)
> 			return ""
> 		} else if err != nil {
> ```

Could simplify to just:
```go
if err ==  pipe.ErrTimeout {
  log.Println("TimeOut for Trace: ", cmd)
  return ""
 }
rtx.PanicOnError(err, "Command %v failed", cmd)
rtx.PanicOnError(ioutil.WriteFile(filename, buff.Bytes(), 0666), "Could not save output to file")
```

**Comment by pboothe** [comment]
___
*[scamper/scamper.go, line 208 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvRVYZc0usAyZ-6fPum:-LvRVYZd1d_J0t9tE8a4:btpb0sb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8138697efcbc33691f79e18dd21ecf22ad7db82f/scamper/scamper.go#L208)):*
> ```Go
> 
> // trace will panic if the operation failed w/ an error not ErrTimeout.
> // It will return an empty string when there is ErrTimeout.
> ```

Please also make `Trace` return `(string, error)` and then propagate the error up the stack to the `CacheEntry`. Using the empty string as a signal value is a bad idea. Instead, we should explicitly keep the invariant that one of the following is always true:
1. `cacheEntry.done` is still open
2. `cacheEntry.error` is not nil (note, you'll need to add a `error: error,` line to `CacheEntry`)
3. `cacheEntry.data` is actual data from a trace

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/51)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[scamper/scamper.go, line 233 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvQunmA9TJdZVl0Ykmk:-Lvf9pTM9Nc-c4Pik3XC:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/6ff41ed4d5158ecd5e9163db43137910ded3c7ad/scamper/scamper.go#L233)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Could simplify to just:
```go
if err ==  pipe.ErrTimeout {
  log.Println("TimeOut for Trace: ", cmd)
  return ""
 }
rtx.PanicOnError(err, "Command %v failed", cmd)
rtx.PanicOnError(ioutil.WriteFile(filename, buff.Bytes(), 0666), "Could not save output to file")
```
</blockquote></details>

Done.
___
*[scamper/scamper.go, line 208 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvRVYZc0usAyZ-6fPum:-LvgCw-06aQ1oWhH7q81:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8138697efcbc33691f79e18dd21ecf22ad7db82f/scamper/scamper.go#L208)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please also make `Trace` return `(string, error)` and then propagate the error up the stack to the `CacheEntry`. Using the empty string as a signal value is a bad idea. Instead, we should explicitly keep the invariant that one of the following is always true:
1. `cacheEntry.done` is still open
2. `cacheEntry.error` is not nil (note, you'll need to add a `error: error,` line to `CacheEntry`)
3. `cacheEntry.data` is actual data from a trace
</blockquote></details>

Done.

**Review by pboothe — CHANGES_REQUESTED** [review]
Please cover the error handling code with tests. It is (demonstrably) hard to reason about, so we want to give ourselves every opportunity to find bugs.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-:-LvgFox79D_5LmyxiOeH:b-akxwfa)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[ipcache/ipcache.go, line 71 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvgEuG_0LvL2GiNOcYa:-LvgEuGa6PL7jUilS9Lp:bh7bj32) ([raw file](https://github.com/m-lab/traceroute-caller/blob/058e618443e720b6a14b01768047c9e12da77c9a/ipcache/ipcache.go#L71)):*
> ```Go
> 		return "", c.err
> 	}
> 	data, err := rc.tracer.Trace(conn, c.timeStamp)
> ```

Let's simplify this into:
```go
c.data, c.err = rc.tracer.Trace(conn, c.timeStamp)
close(c.dataReady)
return c.data, c.err
```
___
*[scamper/scamper.go, line 233 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvQunmA9TJdZVl0Ykmk:-LvgF_T80zdPtB0NeQhr:b8dwxgb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/6ff41ed4d5158ecd5e9163db43137910ded3c7ad/scamper/scamper.go#L233)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please change the condition to:
```go
if err == pipe.ErrTimeout {
```
Testing the text equality of error text is an antipattern. We want to test that the error IS the same as the one that pipe returns on timeout, not whether it has the same text as the error that pipe returns on timeout.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/51)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[ipcache/ipcache.go, line 71 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvgEuG_0LvL2GiNOcYa:-LvgJM7H1mcClP0m6XEC:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/058e618443e720b6a14b01768047c9e12da77c9a/ipcache/ipcache.go#L71)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Let's simplify this into:
```go
c.data, c.err = rc.tracer.Trace(conn, c.timeStamp)
close(c.dataReady)
return c.data, c.err
```
</blockquote></details>

Done.
___
*[scamper/scamper.go, line 233 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvQunmA9TJdZVl0Ykmk:-LvgJNfD83VMcUbeRhPH:bb6un1j) ([raw file](https://github.com/m-lab/traceroute-caller/blob/6ff41ed4d5158ecd5e9163db43137910ded3c7ad/scamper/scamper.go#L233)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

please change the condition to:
```go
if err == pipe.ErrTimeout {
```
Testing the text equality of error text is an antipattern. We want to test that the error IS the same as the one that pipe returns on timeout, not whether it has the same text as the error that pipe returns on timeout.
</blockquote></details>

Done

**Review by pboothe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/51)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[scamper/scamper_test.go, line 149 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvgSJqvAsihp2OVt27W:-LvgSJqwDddNTg56hfvN:b-jodwrt) ([raw file](https://github.com/m-lab/traceroute-caller/blob/45b5ca899597892f38903344f632873020338597/scamper/scamper_test.go#L149)):*
> ```Go
> 
> 	d := Daemon{
> 		AttachBinary:     "echo",
> ```

Please make this "yes" instead of "echo". Otherwise you risk race conditions.

**Review by pboothe — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/51)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[scamper/scamper.go, line 233 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvQunmA9TJdZVl0Ykmk:-Lvl1Liq1PyaPrBOR0pa:bthcx5z) ([raw file](https://github.com/m-lab/traceroute-caller/blob/6ff41ed4d5158ecd5e9163db43137910ded3c7ad/scamper/scamper.go#L233)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Done
</blockquote></details>

Pipe appears to make copies of the errors before returning them. The best we can do is to ensure that the canonical error and the returned error have the same text.

**Comment by pboothe** [comment]
Removing myself as a reviewer and adding Stephen, because I finished working on this high-priority thing while Ya was out, and so have made myself ineligible.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- added a few requests. Some function names are a little confusing, but not for this PR.

> Reviewed 1 of 7 files at r4, 3 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-:-LvlAlEm9_FMES4wXOFT:b-sqg6ho)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe, @stephen-soltesz, and @yachang)

___
*[ipcache/ipcache_test.go, line 164 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-Lvl85nj1CXpR8zt4HQU:-Lvl85nk9TpZa2SEMHMx:b-e0oa2) ([raw file](https://github.com/m-lab/traceroute-caller/blob/44a41f776cdc258b8d8315e66e99537a3c38469c/ipcache/ipcache_test.go#L164)):*
> ```Go
> 			s, err := c.Trace(connection.Connection{RemoteIP: fmt.Sprintf("%d", j)})
> 			expected := fmt.Sprintf("Trace to %d", j)
> 			if j == 90 || j == 33 {
> ```

OMG there are a lot of specific constants in this unit test.

May I request defining int vars above the pausingTracer definition and format them as strings using fmt.Sprintf in the pausingTracer definition, so that the named vars can be used here?
___
*[scamper/scamper.go, line 233 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-LvQunmA9TJdZVl0Ykmk:-Lvl9eUy9l1b9mFw3_bD:b47cjba) ([raw file](https://github.com/m-lab/traceroute-caller/blob/6ff41ed4d5158ecd5e9163db43137910ded3c7ad/scamper/scamper.go#L233)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Pipe appears to make copies of the errors before returning them. The best we can do is to ensure that the canonical error and the returned error have the same text.
</blockquote></details>

i: I agree that's an anti-pattern. We could update our fork of the pipe package to adopt best practice here.
___
*[scamper/scamper.go, line 49 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-Lvl8lEICVsOXmee8_M2:-Lvl8lEICVsOXmee8_M3:b-hhaome) ([raw file](https://github.com/m-lab/traceroute-caller/blob/44a41f776cdc258b8d8315e66e99537a3c38469c/scamper/scamper.go#L49)):*
> ```Go
> 	tracesNotPerformed = promauto.NewCounter(
> 		prometheus.CounterOpts{
> 			Name: "traces_skipped_total",
> ```

This came up with @yachang  -- is there a "total traces" performed metric? We're trying to use the pusher file histogram to see successful traces based on size -- but that's fuzzy. That metric should be part of https://github.com/m-lab/traceroute-caller/issues/19 -- we want to be able to compare one version/config of TC to the next based on number of successful traces (not cached).

Please add a TODO for the metric or just add the metric if it does not exist already.
___
*[scamper/scamper.go, line 234 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-Lvl9U1f7EFPY_C_dphy:-Lvl9U1f7EFPY_C_dphz:bti8kuw) ([raw file](https://github.com/m-lab/traceroute-caller/blob/44a41f776cdc258b8d8315e66e99537a3c38469c/scamper/scamper.go#L234)):*
> ```Go
> 		err = pipe.RunTimeout(cmd, d.ScamperTimeout)
> 		if err != nil && err.Error() == pipe.ErrTimeout.Error() {
> 			log.Println("TimeOut for Trace: ", cmd)
> ```

Will the length of time be known to the reader here?

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/51)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz and @yachang)

___
*[ipcache/ipcache_test.go, line 164 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-Lvl85nj1CXpR8zt4HQU:-LvlFY5i3PaXDmPz-d3x:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/44a41f776cdc258b8d8315e66e99537a3c38469c/ipcache/ipcache_test.go#L164)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

OMG there are a lot of specific constants in this unit test.

May I request defining int vars above the pausingTracer definition and format them as strings using fmt.Sprintf in the pausingTracer definition, so that the named vars can be used here?
</blockquote></details>

Done.
___
*[scamper/scamper.go, line 49 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-Lvl8lEICVsOXmee8_M2:-LvlBfva65h_nbKPOZfG:b-rck1ui) ([raw file](https://github.com/m-lab/traceroute-caller/blob/44a41f776cdc258b8d8315e66e99537a3c38469c/scamper/scamper.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This came up with @yachang  -- is there a "total traces" performed metric? We're trying to use the pusher file histogram to see successful traces based on size -- but that's fuzzy. That metric should be part of https://github.com/m-lab/traceroute-caller/issues/19 -- we want to be able to compare one version/config of TC to the next based on number of successful traces (not cached).

Please add a TODO for the metric or just add the metric if it does not exist already.
</blockquote></details>

Added issue #53 

Will address it in next PR 
___
*[scamper/scamper.go, line 234 at r6](https://reviewable.io/reviews/m-lab/traceroute-caller/51#-Lvl9U1f7EFPY_C_dphy:-LvlGaiR2nzYD5zp5sLS:b-qdlx3e) ([raw file](https://github.com/m-lab/traceroute-caller/blob/44a41f776cdc258b8d8315e66e99537a3c38469c/scamper/scamper.go#L234)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Will the length of time be known to the reader here?
</blockquote></details>

Added the time to the log message

**Pull request merged**
