### PR TITLE
implement cached test

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/33)

### CODE REVIEW

**Review by pboothe — COMMENTED** [review]
Please get things back to 100% coverage.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-:-Lrp7qc8Dd7dvsAeu--K:b-yppx3u)* status: 0 of 1 approvals obtained (waiting on @pboothe)

**Review by pboothe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/33)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[ipcache/ipcache.go, line 38 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LrpAnqD0ix-G71nc-rh:-LrpAnqD0ix-G71nc-ri:b-ep85jy) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/ipcache/ipcache.go#L38)):*
> ```Go
> 
> // GetTrace returns test content in []byte given a connection and tracer
> func (rc *RecentIPCache) GetTrace(conn connection.Connection, sc scamper.Tracer) {
> ```

`GetTrace` should either return a string or it should have a different name.
___
*[ipcache/ipcache.go, line 54 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lrp8lBLAPb4XYo4fNJC:-Lrp8lBLAPb4XYo4fNJD:b-ko6bvl) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/ipcache/ipcache.go#L54)):*
> ```Go
> 		rc.mu.Unlock()
> 	}
> 	<-rc.cache[ip].done
> ```

You are accessing the map outside of the mutex lock. Change the line `_, ok := rc.cache[ip]` to be `c,ok := rc.cache[ip]` and then change this line to `<-c.done`  You will also have to set the value of `c` inside the `if`
___
*[ipcache/ipcache.go, line 56 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lrp98IK51oy0z4mrVVm:-Lrp98ILEwdvs_z8_QBC:b69kd16) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/ipcache/ipcache.go#L56)):*
> ```Go
> 	<-rc.cache[ip].done
> 	if ok {
> 		sc.CreateCacheTest(conn, time.Now(), rc.cache[ip].data)
> ```

Same thing here regarding unsafe `map` access.
___
*[ipcache/ipcache.go, line 64 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lrp9MmR8duFDpcnJMi_:-Lrp9MmS3q4RloLARBgM:bypao3o) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/ipcache/ipcache.go#L64)):*
> ```Go
> func New(ctx context.Context) *RecentIPCache {
> 	m := &RecentIPCache{}
> 	m.mu.Lock()
> ```

No need for `Lock` and `Unlock` inside of `New`
___
*[scamper/scamper.go, line 144 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lrp9tRi-2_UiH3HLloA:-Lrp9tRi-2_UiH3HLloB:bn82vut) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/scamper/scamper.go#L144)):*
> ```Go
> 	// metadata, this is the place to do it.
> 	//
> 	// TODO: decide what other metadata to add to the traceroute output. If we
> ```

This adds enough metadata that I would like to have:
```go
type Metadata struct {
  UUID, TracerouteCallerVersion string
  CachedUUID string `json:ignoremissing`
  CachedResult bool
}
```
And then we can use `json.Marshall` to put it into a string.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/33)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[ipcache/ipcache.go, line 38 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LrpAnqD0ix-G71nc-rh:-LrtCb9xC5E-KONGZANC:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/ipcache/ipcache.go#L38)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

`GetTrace` should either return a string or it should have a different name.
</blockquote></details>

Done.
___
*[ipcache/ipcache.go, line 54 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lrp8lBLAPb4XYo4fNJC:-LrtGpCa9GCM445t1GaJ:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/ipcache/ipcache.go#L54)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

You are accessing the map outside of the mutex lock. Change the line `_, ok := rc.cache[ip]` to be c,ok := rc.cache[ip]` and then change this line to `<-c.done`  You will also have to set the value of `c` inside the `if`
</blockquote></details>

Done.
___
*[ipcache/ipcache.go, line 56 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lrp98IK51oy0z4mrVVm:-LrtFHWJ8__QSVPtAuNf:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/ipcache/ipcache.go#L56)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Same thing here regarding unsafe `map` access.
</blockquote></details>

Done.
___
*[ipcache/ipcache.go, line 64 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lrp9MmR8duFDpcnJMi_:-LrtEI8BEJXqD0UBZpvq:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/ipcache/ipcache.go#L64)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

No need for `Lock` and `Unlock` inside of `New`
</blockquote></details>

Done.
___
*[scamper/scamper.go, line 144 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lrp9tRi-2_UiH3HLloA:-LrtBpiU8mm9xr9CyOPQ:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0a9a31be90cca3bb8df23229e48319fc1c84efe9/scamper/scamper.go#L144)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This adds enough metadata that I would like to have:
```go
type Metadata struct {
  UUID, TracerouteCallerVersion string
  CachedUUID string `json:ignoremissing`
  CachedResult bool
}
```
And then we can use `json.Marshall` to put it into a string.
</blockquote></details>

Done.

**Comment by pboothe** [comment]
___
*[ipcache/ipcache.go, line 49 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LrtI1Zj0Pc6pyORNSNE:-LrtI1Zj0Pc6pyORNSNF:b5heijw) ([raw file](https://github.com/m-lab/traceroute-caller/blob/3d79664a0fbd7d6de3960753d3c8cea25d785575/ipcache/ipcache.go#L49)):*
> ```Go
> 		rc.mu.Unlock()
> 
> 		rc.cache[ip].data = sc.Trace(conn, rc.cache[ip].timeStamp)
> ```

You are accessing the map outside of the mutex lock.

**Comment by pboothe** [comment]
___
*[scamper/scamper.go, line 168 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LrtIGiD5hLM204g09QV:-LrtIGiD5hLM204g09QW:b-qpit7e) ([raw file](https://github.com/m-lab/traceroute-caller/blob/3d79664a0fbd7d6de3960753d3c8cea25d785575/scamper/scamper.go#L168)):*
> ```Go
> }
> 
> func ExtractUUID(metaline string) string {
> ```

Now you can json.Unmarshall into a Metadata struct instead of casting a map!

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/33)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 49 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LrtI1Zj0Pc6pyORNSNE:-LrtIXqi9232QtS77_Sn:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/3d79664a0fbd7d6de3960753d3c8cea25d785575/ipcache/ipcache.go#L49)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

You are accessing the map outside of the mutex lock.
</blockquote></details>

Done.

**Comment by pboothe** [comment]
___
*[ipcache/ipcache.go, line 49 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LrtI1Zj0Pc6pyORNSNE:-Lru2OhaEsUcrNM7r5Wk:bk994qp) ([raw file](https://github.com/m-lab/traceroute-caller/blob/3d79664a0fbd7d6de3960753d3c8cea25d785575/ipcache/ipcache.go#L49)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please do the following:
```go
c = &CacheTest{
  timeStamp: time.Now(),
  done:      make(chan struct{}),
}
rc.cache[ip] = c
rc.mu.Unlock()

ct.data := sc.Trace(conn, c.timeStamp)
close(c.done)
```

**Comment by pboothe** [comment]
___
*[connectionpoller/connectionpoller_test.go, line 137 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lru3agJ-YJVb0aLxXoJ:-Lru3agJ-YJVb0aLxXoK:b-8aa6ld) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fe671208961b9be6d803e206e40919ac65d932e5/connectionpoller/connectionpoller_test.go#L137)):*
> ```Go
> 	connPoller := New(cache)
> 	var tt testTracer
> 	connPoller.TraceClosedConnections(&tt)
> ```

You should be able to verify that it calls tt.Trace for a few connections by giving the `connPoller` a fake `finder`

**Comment by pboothe** [comment]
___
*[scamper/scamper.go, line 168 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LrtIGiD5hLM204g09QV:-Lru4QTB4vEP0JBHQlY0:b-pqzjmg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/3d79664a0fbd7d6de3960753d3c8cea25d785575/scamper/scamper.go#L168)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Now you can json.Unmarshall into a Metadata struct instead of casting a map!
</blockquote></details>

Please do something like:
```go
var metaResult Metadata
err := json.Unmarshal([]byte(metaline), &metaResult)
if err != nil {
  log.Println("Could not parse cached results:", metaline)
  return ""
}
return metaResult.UUID
```
It saves lines and is more typesafe

**Comment by pboothe** [comment]
___
*[scamper/scamper.go, line 186 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lru57EzBB4UHCx3ZgTu:-Lru57EzBB4UHCx3ZgTv:b-cpn3wa) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fe671208961b9be6d803e206e40919ac65d932e5/scamper/scamper.go#L186)):*
> ```Go
> 
> 	// remove the first line of cachedTest
> 	split := strings.Index(cachedTest, "\n")
> ```

Please verify that this is not -1.

**Review by pboothe — CHANGES_REQUESTED** [review]
Last few comments!  This is looking good....

> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-:-Lru5Iz39SeQtXAVXYuc:bizay6)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[ipcache/ipcache.go, line 67 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lru4K19CswrfNcXKzo0:-Lru4K19CswrfNcXKzo1:byhmj3l) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fe671208961b9be6d803e206e40919ac65d932e5/ipcache/ipcache.go#L67)):*
> ```Go
> }
> 
> func (rc *RecentIPCache) GetCacheLenght() int {
> ```

Length is misspelled
___
*[ipcache/ipcache.go, line 72 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lru471E4bDemAyg9Ugi:-Lru471E4bDemAyg9Ugj:b-lz04na) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fe671208961b9be6d803e206e40919ac65d932e5/ipcache/ipcache.go#L72)):*
> ```Go
> 
> func (rc *RecentIPCache) GetTestContent(ip string) string {
> 	rc.mu.RLock()
> ```

just do `defer rc.mu.Runlock()`

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/33)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[connectionpoller/connectionpoller_test.go, line 137 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lru3agJ-YJVb0aLxXoJ:-LruBmWA10bgxPIa7l23:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fe671208961b9be6d803e206e40919ac65d932e5/connectionpoller/connectionpoller_test.go#L137)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

You should be able to verify that it calls tt.Trace for a few connections by giving the `connPoller` a fake `finder`
</blockquote></details>

Done.
___
*[ipcache/ipcache.go, line 49 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LrtI1Zj0Pc6pyORNSNE:-LruCtxABfgcmJ-DfXhB:bb6un1j) ([raw file](https://github.com/m-lab/traceroute-caller/blob/3d79664a0fbd7d6de3960753d3c8cea25d785575/ipcache/ipcache.go#L49)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please do the following:
```go
c = &CacheTest{
  timeStamp: time.Now(),
  done:      make(chan struct{}),
}
rc.cache[ip] = c
rc.mu.Unlock()

ct.data := sc.Trace(conn, c.timeStamp)
close(c.done)
```

 

</blockquote></details>

Done
___
*[ipcache/ipcache.go, line 67 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lru4K19CswrfNcXKzo0:-LruCuny1CyqUelz_k3x:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fe671208961b9be6d803e206e40919ac65d932e5/ipcache/ipcache.go#L67)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Length is misspelled
</blockquote></details>

Done.
___
*[ipcache/ipcache.go, line 72 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lru471E4bDemAyg9Ugi:-LruDdVaCWTgemHFWjGk:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fe671208961b9be6d803e206e40919ac65d932e5/ipcache/ipcache.go#L72)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

just do `defer rc.mu.Runlock()`
</blockquote></details>

Done.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/33)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[scamper/scamper.go, line 168 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LrtIGiD5hLM204g09QV:-LrxxO2y0DQJJsobfi5t:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/3d79664a0fbd7d6de3960753d3c8cea25d785575/scamper/scamper.go#L168)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please do something like:
```go
var metaResult Metadata
err := json.Unmarshal([]byte(metaline), &metaResult)
if err != nil {
  log.Println("Could not parse cached results:", metaline)
  return ""
}
return metaResult.UUID
```
It saves lines and is more typesafe
  
 

</blockquote></details>

Done.
___
*[scamper/scamper.go, line 186 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-Lru57EzBB4UHCx3ZgTu:-Lrxz-dY3zRA1FjJptOg:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/fe671208961b9be6d803e206e40919ac65d932e5/scamper/scamper.go#L186)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please verify that this is not -1.
</blockquote></details>

Done.

**Review by pboothe — APPROVED** [review]
One comment, and then once coverage is 100% it :lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-:-Lryi7MTELwdulF6X1dM:bo8tnik)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 51 at r5](https://reviewable.io/reviews/m-lab/traceroute-caller/33#-LryhHiG1_gy1u6A1W4n:-LryhHiG1_gy1u6A1W4o:bps2zus) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7aae0de3b62a9fcb64be7f68dde430a17e575c25/ipcache/ipcache.go#L51)):*
> ```Go
> 
> 		nc.data = sc.Trace(conn, nc.timeStamp)
> 		close(nc.done)
> ```

add "return" here, then you can change the rest to:
```go
rc.mu.Unlock()
<-c.done
cachedData := c.data
dsc.CreateCacheTest(conn, time.Now(), cachedData)
```

No `else` block, no `if` statement - everything is simpler.  Also you don't need a reader lock to access `c`, jJust to access the map. So you can eliminate that Rlock/Runlock code too!

**Pull request merged**
