### PR TITLE
Code cleanup and some refactoring

### PR DESCRIPTION
**Pull request by gfr10598**
Updates tests to include file/linenum
Updates tests to avoid when not on linux
refactors generateFilename
starts extracting code that is common between scamper and scamper-daemon

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/104)

### CODE REVIEW

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/104)* status: 0 of 1 approvals obtained

**Comment by SaiedKazemi** [comment]
*[a discussion](https://reviewable.io/reviews/m-lab/traceroute-caller/104#-McB6zls9h2svvMBaGv_:-McB6zls9h2svvMBaGva:bb6ywmx) (no related file):*
LGTM

---

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/104)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by gfr10598** [comment]
obsolete

**Pull request closed without merging**
