### PR TITLE
Create Dockerfile to build scamper binary

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/2)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/2#-L_OsWu52X9d66VwpDmJ:-L_OsWu52X9d66VwpDmK:b67fx29) ([raw file](https://github.com/m-lab/traceroute-caller/blob/da356fb7cd1ba702f74dd19b34032e221aa044a0/Dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:latest
> ```

Will this work with alpine instead?  It is much lighter weight for basing tools.

Also, add a TODO to separate the build environment from the final docker container.  See https://github.com/m-lab/tcp-info/blob/master/Dockerfile, though that isn't a great example because zstd uses dynamically linked libraries (for now) that end up requiring ubuntu for now.
___
*[Dockerfile, line 10 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/2#-L_Os9JS4M3OKB9ehSKc:-L_Os9JS4M3OKB9ehSKd:bb6xukg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/da356fb7cd1ba702f74dd19b34032e221aa044a0/Dockerfile#L10)):*
> ```Dockerfile
> RUN mkdir /source
> ADD . /go/src/github.com/m-lab/traceroute-caller
> RUN mv /go/src/github.com/m-lab/traceroute-caller/vendor/scamper/scamper-cvs-20190113 /source
> ```

Is this mv useful?  Maybe just cd directly to the scamper-cvs-20190113 directory?
___
*[Dockerfile, line 13 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/2#-L_OsGn6DeWzyupcSFuS:-L_OsGn6DeWzyupcSFuT:b-w3orpi) ([raw file](https://github.com/m-lab/traceroute-caller/blob/da356fb7cd1ba702f74dd19b34032e221aa044a0/Dockerfile#L13)):*
> ```Dockerfile
> RUN chmod +x /source/scamper-cvs-20190113/configure
> RUN /source/scamper-cvs-20190113/configure
> RUN cd /source/scamper-cvs-20190113/
> ```

Suggest you do this before doing anything in the directory.  Then chmod, configure, etc, locally.
___
*[Dockerfile, line 19 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/2#-L_OsTVZ0R52NXDuOmeo:-L_OsTVZ0R52NXDuOmep:b-5x2m7m) ([raw file](https://github.com/m-lab/traceroute-caller/blob/da356fb7cd1ba702f74dd19b34032e221aa044a0/Dockerfile#L19)):*
> ```Dockerfile
> 
> RUN chmod +x /usr/local/bin/scamper
> RUN chmod 4755 /usr/local/bin/scamper
> ```

If doing this, then the previous line is irrelevant.

**Review by gfr10598 — COMMENTED** [review]
:lgtm:  after comments.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/2#-:-L_OvZOR1MbBS0JlrT_4:b-nsu5h7)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

___
*[Dockerfile, line 10 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/2#-L_Os9JS4M3OKB9ehSKc:-L_Ow11HDhMSi-qhS2Y3:b-eyv37l) ([raw file](https://github.com/m-lab/traceroute-caller/blob/da356fb7cd1ba702f74dd19b34032e221aa044a0/Dockerfile#L10)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is this mv useful?  Maybe just cd directly to the scamper-cvs-20190113 directory?
</blockquote></details>

I tried. For unknown reason, it did not work.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @yachang)

___
*[Dockerfile, line 19 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/2#-L_OsTVZ0R52NXDuOmeo:-L_Ow8oP3cbXFn03cgMz:b2ni9ah) ([raw file](https://github.com/m-lab/traceroute-caller/blob/da356fb7cd1ba702f74dd19b34032e221aa044a0/Dockerfile#L19)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

If doing this, then the previous line is irrelevant.
</blockquote></details>

ok

**Pull request merged**
