### PR TITLE
Prepare traceroute-caller for supporting hop annotations

### PR DESCRIPTION
**Pull request by SaiedKazemi**
Although this commit seems big, it does not change the behavior
of traceroute-caller (hence this work was done in feature branch
sandbox-saied-noop). Here's a summary of the changes:

  - Remove poll mode because it's not used and its package
    testing was intermittently failing due to race conditions.
  - Remove legacy debug code for scamper-daemon-with-scamper-backup.
  - Make changes to comply with Go style guidelines with respect
    to comments, error messages, etc.
  - Improve package testing code and coverage.
  - Introduce a no-op hopannotation code to be followed with
    an actual implementation in the next commit.

The changes were tested with "go test ./... -race" and
"docker-compose up" on my local workstation.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/119)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> Reviewed 19 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/119)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[.dockerignore, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVo54u5GMKQciTMcjP:-MhVo54u5GMKQciTMcjQ:b3h3yz0) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/.dockerignore#L1)):*
> ```ignore
> **/local
> ```

Is this intended or accidental?
___
*[caller_test.go, line 48 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVp-fT12CE3sUEMxDf:-MhVp-fUDRuvPB89q_4r:bb7u87a) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/caller_test.go#L48)):*
> ```Go
> 		cancel()
> 	}()
> 	main()
> ```

BTW, it is unclear to me whether this test passes if main exits with rtx.Must
___
*[connection/connection.go, line 82 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVpbsy6Nnj7lHTXuyZ:-MhVpbsy6Nnj7lHTXuy_:bb9qwdd) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connection/connection.go#L82)):*
> ```Go
> }
> 
> // NewLocalIPs makes an object that can convert src and dst into local
> ```

How about NewLocalRemoteLabeller?
___
*[connectionlistener/connectionlistener.go, line 29 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVq7KAElwsTOLZC-C7:-MhVq7KAElwsTOLZC-C8:b-epu9jm) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener.go#L29)):*
> ```Go
> 	connsLock    sync.Mutex
> 	conns        map[string]connection.Connection
> 	ipCache      *ipcache.RecentIPCache
> ```

Add comment specifying whether ipCache, creator, and hopAnnotator are immutable after creation, and if not, how they are managed.  (I might not have noticed if you hadn't changed the name of the lock.)
___
*[connectionlistener/connectionlistener.go, line 45 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVqVfaCMC0lL43m3I1:-MhVqVfaCMC0lL43m3I2:bxmhxq6) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener.go#L45)):*
> ```Go
> 	}
> 
> 	cl.connsLock.Lock()
> ```

If this only protects the map, then move it immediately above the map access.
___
*[connectionlistener/connectionlistener.go, line 62 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVqkLMEt5ToT8tkywA:-MhVqkLMEt5ToT8tkywB:b-mr0c0e) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener.go#L62)):*
> ```Go
> // Note that this function doesn't use timestamp.
> func (cl *connectionListener) Close(ctx context.Context, timestamp time.Time, uuid string) {
> 	cl.connsLock.Lock()
> ```

I really can hardly wait until the connection map goes away!
___
*[connectionlistener/connectionlistener.go, line 79 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVqqYx2f8Mj2s_bWax:-MhVqqYx2f8Mj2s_bWay:b3qzs68) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener.go#L79)):*
> ```Go
> }
> 
> func (cl *connectionListener) traceAnnotateArchive(ctx context.Context, conn connection.Connection) {
> ```

traceAnnotateAndArchive. Otherwise it is a bit unclear how to interpret the name.
___
*[connectionlistener/connectionlistener_test.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVrDE67BJQAvZmJoeL:-MhVrDE67BJQAvZmJoeM:b96qd1k) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener_test.go#L33)):*
> ```Go
> 	// We assign these to conn.Cookie to test different kinds of
> 	// errors in our fake Trace().
> 	traceFailed      = int64(0x1001)
> ```

This is a bit obscure.  Can you improve the comment to be more clear?
___
*[connectionlistener/connectionlistener_test.go, line 62 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVrVZXC-OUFccG4dru:-MhVrVZXC-OUFccG4drv:b-w8ymia) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener_test.go#L62)):*
> ```Go
> 	switch conn.Cookie {
> 	case fmt.Sprintf("%x", traceFailed):
> 		traceFile = "testdata/trace-non-existent.jsonl"
> ```

I think this would be clearer with a map from cookie to filename, rather than switch.
___
*[hopannotation/hopannotation.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVs42Z7wWwRU3xXBdy:-MhVs42Z7wWwRU3xXBdz:b8tnu0k) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/hopannotation/hopannotation.go#L1)):*
> ```Go
> // Package hopannotation handles hop annotation and archiving by
> ```

Since I'm quite tired, how about making this a trivial type with empty methods bodies, or maybe no methods at all - just type HopCache struct{} with no methods?
___
*[tracer/scamper.go, line 42 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVsfDc1WZBZw0mLLE1:-MhVsfDc1WZBZw0mLLE2:b-ifccls) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/tracer/scamper.go#L42)):*
> ```Go
> 	c, err := strconv.ParseUint(cookie, 16, 64)
> 	if err != nil {
> 		// TODO(SaiedKazemi): Add metric here.
> ```

Can this use a different error type for an existing error metric?  Might be best to add the metric.Inc() now, here and above.
___
*[tracer/scamper.go, line 83 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVspaW6slLP4MQaODk:-MhVspaW6slLP4MQaODl:b-7xvid0) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8c45dc9b5b5521b4d622d48cfaaa4d5f95096e64/tracer/scamper.go#L83)):*
> ```Go
> // called binaries have a much smaller "blast radius".
> func (s *Scamper) Trace(conn connection.Connection, t time.Time) (out []byte, err error) {
> 	// TODO Is this still useful?  Does shx.PipeJob we ever panic?
> ```

Yay!!

**Review by gfr10598 — APPROVED** [review]
Skimmed again.  I think it :lgtm: with the requested changes.  I won't likely be able to do any more before Monday.

> Reviewed 3 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-:-MhYQJfT3GkpzSUY8pyW:b-re289a)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Comment by SaiedKazemi** [comment]
___
*[.dockerignore, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVo54u5GMKQciTMcjP:-MhZVaKA8vCFRgKHVPI_:b-4uvbsb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/.dockerignore#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is this intended or accidental?
</blockquote></details>

This is intended.  It excludes all directories called "local", created during testing, from the context sent to the Docker daemon.

**Comment by SaiedKazemi** [comment]
___
*[caller_test.go, line 48 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVp-fT12CE3sUEMxDf:-MhZX2_jDqS_Jl0eLLUR:br0tch2) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/caller_test.go#L48)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

BTW, it is unclear to me whether this test passes if main exits with rtx.Must
</blockquote></details>

This has always been there and, so far, it hasn't been an issue.  That said, I'd like to rework some parts of call_test.go but it's not urgent right now.

**Comment by SaiedKazemi** [comment]
___
*[connection/connection.go, line 82 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVpbsy6Nnj7lHTXuyZ:-MhZY89hEcUoB6zZpjcA:b-kc9lv5) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connection/connection.go#L82)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

How about NewLocalRemoteLabeller?
</blockquote></details>

NewLocalIPs was actually the name that we came up with a few weeks ago.  NewLocalRemoteLabeller is too long and difficult to read.  I think NewLocalRemoteIPs is a good compromise and I will change it that.

**Comment by SaiedKazemi** [comment]
___
*[connectionlistener/connectionlistener.go, line 29 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVq7KAElwsTOLZC-C7:-MhZbZet4JeCnB83yEMp:b-v4v806) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener.go#L29)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add comment specifying whether ipCache, creator, and hopAnnotator are immutable after creation, and if not, how they are managed.  (I might not have noticed if you hadn't changed the name of the lock.)
</blockquote></details>

These are explained in ipcache.New(), connection.NewLocalRemoteIPs(), and hopannotation.New() respectively.  To avoid multiple explanations that can get out of sync and confusing, I added a comment to refer to these functions for details.

**Comment by SaiedKazemi** [comment]
___
*[connectionlistener/connectionlistener.go, line 45 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVqVfaCMC0lL43m3I1:-MhZeHNMBYaPqJkZDk5x:bi1gszl) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener.go#L45)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

If this only protects the map, then move it immediately above the map access.
</blockquote></details>

The original code locks it before calling cl.creator.FromSockID(*id) and I didn't want to change that logic.  I will add a TODO comment to revisit this and determine if we can move the lock to right before map access.

**Comment by SaiedKazemi** [comment]
___
*[connectionlistener/connectionlistener.go, line 62 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVqkLMEt5ToT8tkywA:-MhZfB9a9O4sA4DnrS4n:b-f7ohoi) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener.go#L62)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I really can hardly wait until the connection map goes away!
</blockquote></details>

Me too :)

**Comment by SaiedKazemi** [comment]
___
*[connectionlistener/connectionlistener_test.go, line 62 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVrVZXC-OUFccG4dru:-MhZiq6JEjslAcZAakQp:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener_test.go#L62)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this would be clearer with a map from cookie to filename, rather than switch.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[hopannotation/hopannotation.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVs42Z7wWwRU3xXBdy:-Mh_34Ax3Qqp-kCBpnTM:b-l5p5ee) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/hopannotation/hopannotation.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Since I'm quite tired, how about making this a trivial type with empty methods bodies, or maybe no methods at all - just type HopCache struct{} with no methods?
</blockquote></details>

This file will be soon be replaced by the real implementation but I made changed it to empty structs as you've suggested.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 42 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVsfDc1WZBZw0mLLE1:-Mh_5O6n5JxCV-zJGG7Y:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/tracer/scamper.go#L42)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can this use a different error type for an existing error metric?  Might be best to add the metric.Inc() now, here and above.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 83 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVspaW6slLP4MQaODk:-Mh_5nD28i64j6CSnsL0:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/8c45dc9b5b5521b4d622d48cfaaa4d5f95096e64/tracer/scamper.go#L83)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Yay!!
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[connectionlistener/connectionlistener.go, line 79 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVqqYx2f8Mj2s_bWax:-MhZfR1s09tIyH2BGORQ:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener.go#L79)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

traceAnnotateAndArchive. Otherwise it is a bit unclear how to interpret the name.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[connectionlistener/connectionlistener_test.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/119#-MhVrDE67BJQAvZmJoeL:-MhZh3uJ56WyZEGBoW1T:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/48e278a860cf44528466e2753671e6eea8eb922d/connectionlistener/connectionlistener_test.go#L33)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This is a bit obscure.  Can you improve the comment to be more clear?
</blockquote></details>

Done.

**Pull request merged**
