### PR TITLE
Fix connection listener

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/40)

### CODE REVIEW

**Comment by pboothe** [comment]
Part of https://github.com/m-lab/traceroute-caller/issues/38

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/40)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[ipcache/ipcache.go, line 113 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/40#-LuZ2YGV38KWIe0ae8Ix:-LuZ2YGW1qjmVrm3Y5qy:b-fs66ky) ([raw file](https://github.com/m-lab/traceroute-caller/blob/b2be82de00a29c5b757f2536a1d57e366042c5cb/ipcache/ipcache.go#L113)):*
> ```Go
> 
> // Add an IP to the cache.
> func (m *RecentIPCache) Add(ip string) {
> ```

We can delete this func and below func

**Review by yachang — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/40#-:-LuZDx0yEqDH2IV3RZ9Z:bg7igkv)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

**Review by yachang — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/40#-:-LuZDykhEJFcd4iw1JF8:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe)

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/traceroute-caller/issues/38

**Pull request merged**
