### PR TITLE
Update "Local Development" instructions in README.md

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/84)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Thank you for the updates! There's a choice to make about formatting the commands with `$`.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/84#-:-MVs7RyS-qaxmw0JMIde:b-ebslor)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[README.md, line 26 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/84#-MVs4oHl83Io6DZFj_7P:-MVs4oHl83Io6DZFj_7Q:b-3atrkb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7458148df160f229758d87454ac6a05b7762d820/README.md#L26)):*
> ```Markdown
> 
> ```sh
> $ docker-compose up
> ```

One of the things that we should document as part of our "conventions docs" to be helpful is "typical development environment." I use VSCode for most of my work, with a number of extensions, including "markdownlint". I've come to rely on this linter to tell me what's helpful or not in markdown docs. I've found that it does a good job of keeping the text readable whether it's generated output (e.g. html) or in it's raw text format.

In this case, `markdownlint` cares about two cases where the `$` is present for `sh` text blocks.

* When the command uses `$` it should show output. For example:

`MD014/commands-show-output: Dollar signs used before commands without showing output`

* When the command does not use `$` it is much easier for users following along to copy/paste the command.

Because this README is structured as a HOWTO, I suggest leaving the commands without `$`. (I personally prefer HOWTOs that make it easy to copy the commands I'm supposed to run) If you prefer to keep the `$`, then I think we should use the guidance from markdownlint and include some output in the example.

**Comment by SaiedKazemi** [comment]
Sorry, I didn't mean to impose my choice by adding `$` to the commands.  I just noticed that `docker-compose version` had `$` and added it to the rest for consistency (please feel free to remove them).

**Comment by SaiedKazemi** [comment]
___
*[README.md, line 26 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/84#-MVs4oHl83Io6DZFj_7P:-MVsCggL69VfBbulQoHX:b-h6dzzb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7458148df160f229758d87454ac6a05b7762d820/README.md#L26)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

One of the things that we should document as part of our "conventions docs" to be helpful is "typical development environment." I use VSCode for most of my work, with a number of extensions, including "markdownlint". I've come to rely on this linter to tell me what's helpful or not in markdown docs. I've found that it does a good job of keeping the text readable whether it's generated output (e.g. html) or in it's raw text format.

In this case, `markdownlint` cares about two cases where the `$` is present for `sh` text blocks.

* When the command uses `$` it should show output. For example:

`MD014/commands-show-output: Dollar signs used before commands without showing output`

* When the command does not use `$` it is much easier for users following along to copy/paste the command.

Because this README is structured as a HOWTO, I suggest leaving the commands without `$`. (I personally prefer HOWTOs that make it easy to copy the commands I'm supposed to run) If you prefer to keep the `$`, then I think we should use the guidance from markdownlint and include some output in the example.
</blockquote></details>

Thanks for the context.  It's now clear why some commands have `$` and some don't.  I like this style and suggest that we all adopt it (although we use different development environments).

**Review by stephen-soltesz — COMMENTED** [review]
There's nothing to apologize for! I'm confused by your comment. I'm requesting that you please choose one approach or the other. Right now it's a mixture of both.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/84#-:-MVv65SYBi48SLrkVwVt:b-4aqut7)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by SaiedKazemi — COMMENTED** [review]
Removed '$ ' from the commands that we don't show their output.

**Review by stephen-soltesz — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/84)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Pull request merged**
