### PR TITLE
Remove paris traceroute and add latency metric

### PR DESCRIPTION
**Pull request by gfr10598**
We should also change the deployment in k8s-support to

1. use the scamper process instead of daemon
2. change trace timeout to 30m
3. change cache timeout to 30m

Also, see Issue #102 

Testing:
  will test with manual deployment to sandbox

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/103)

### CODE REVIEW

**Review by gfr10598 — COMMENTED** [review]
- args:
        - -prometheusx.listen-address=$(PRIVATE_IP):9992
        - -outputPath=/var/spool/ndt/traceroute
        - -uuid-prefix-file=/var/local/uuid/prefix
        - -poll=false
        - -tcpinfo.eventsocket=/var/local/tcpinfoeventsocket/tcpevents.sock
        - -tracetool=scamper
        env:
        - name: PRIVATE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: measurementlab/traceroute-caller:gfr-paris-and-latency
        imagePullPolicy: Always

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/103#-:-McAcGSsEO5Qve4VV5n9:b-xe8znm)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

**Comment by SaiedKazemi** [comment]
___
*[tracer/tracer.go, line 25 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/103#-McB07SY0pw6kPFqht-d:-McB07SY0pw6kPFqht-e:b-j9zb3a) ([raw file](https://github.com/m-lab/traceroute-caller/blob/c6be12d08c1a0fa3ecb39b0cf0f6f3ce12818fa2/tracer/tracer.go#L25)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 				1, 1.47, 2.15, 3.16, 4.64, 6.81,
> 				10, 14.7, 21.5, 31.6, 46.4, 68.1,
> 				100, 147, 215, 316, 464, 681,
> 				1000, 1470, 2150, 3160, 4640, 6810,
> ```
</details>

Can we add a comment about these sequences?  Maybe it's obvious to everyone, but not to me.

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/103)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/103)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[tracer/tracer.go, line 25 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/103#-McB07SY0pw6kPFqht-d:-McBR6iq1dyIO0p6K8mR:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/c6be12d08c1a0fa3ecb39b0cf0f6f3ce12818fa2/tracer/tracer.go#L25)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

> ```
> 				1, 1.47, 2.15, 3.16, 4.64, 6.81,
> 				10, 14.7, 21.5, 31.6, 46.4, 68.1,
> 				100, 147, 215, 316, 464, 681,
> 				1000, 1470, 2150, 3160, 4640, 6810,
> ```
Can we add a comment about these sequences?  Maybe it's obvious to everyone, but not to me.
</blockquote></details>

Done.

**Review by gfr10598 — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/103)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Review by SaiedKazemi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/103)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
