### PR TITLE
Add comments and a check or two to the dockerfile.

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/56)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/56)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @stephen-soltesz)

___
*[Dockerfile, line 20 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/56#-Lvr59Lm5OIvhZuHjafK:-Lvr59Ln3q1hBQ9geN6P:b9yscge) ([raw file](https://github.com/m-lab/traceroute-caller/blob/798659e8e83314360fc94cffc16e2120bad703e9/Dockerfile#L20)):*
> ```Dockerfile
> # all the other packages are for the build processes.
> RUN apt-get update && \
>     apt-get install -y iproute2 make coreutils autoconf libtool git build-essential && \
> ```

Is it possible to remove the build tools after build is complete?

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/56)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[Dockerfile, line 20 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/56#-Lvr59Lm5OIvhZuHjafK:-LvrDUDGBt6P3oikoayx:b-83330z) ([raw file](https://github.com/m-lab/traceroute-caller/blob/798659e8e83314360fc94cffc16e2120bad703e9/Dockerfile#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it possible to remove the build tools after build is complete?
</blockquote></details>

PTAL!

**Review by stephen-soltesz — APPROVED** [review]
Nice. :lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/56#-:-LvrDYqt-t6vojhiY9ux:bxsbkqo)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/56)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by pboothe** [comment]
Found a rare race condition! ( #57 )

Re-running tests. Will submit once tests are green.

**Pull request merged**
