### PR TITLE
Refactor traceroute-caller source code

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit refactors traceroute-caller code to make the code
easier to read and maintain, and also to make it more conformant
with Go style guidelines.

There is no change in the application logic.

This is a work in progress and will be followed by other commits.
Specifically, package testing code that is missing from this
commit will be added soon.

The main purpose of this commit is to facilitate the review
process.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/127)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Some quick feedback.

I feel quite strongly about the unsuitability of default value logic in `New` functions. So, this PR may not be the place to resolve those differences but please let's make sure we do.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-:-MmsmzhFA3IG0L2ufuOV:b-c14bve)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

___
*[caller.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsib1R7BOTow-8ZE9x:-Mmsib1R7BOTow-8ZE9y:b-v38xqm) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/caller.go#L33)):*
> ```Go
> 	log.SetFlags(log.LstdFlags | log.Lshortfile)
> 	flag.Parse()
> 	if err := flagx.ArgsFromEnv(flag.CommandLine); err != nil {
> ```

Out of curiosity, why remove `rtx.Must`? This was designed to facilitate unit testing of main and other scenarios where error handling is otherwise fatal. What was clear in one line is now three lines. What is gained by this change?
___
*[caller.go, line 39 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsjthd78Kec8n0wRtD:-Mmsjthd78Kec8n0wRtE:b-wnzvh3) ([raw file](https://github.com/m-lab/traceroute-caller/blob/61acbe013388ebb3599bc201b89f5bf5f128dc4e/caller.go#L39)):*
> ```Go
> 	//     configuration file in textproto format that would support
> 	//     all scamper and its command flags.
> 	scamperBin          = flag.String("scamper.bin", "scamper", "The path to the scamper binary.")
> ```

I'm confused. Why move flags to individual packages?
___
*[hopannotation/hopannotation.go, line 106 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-MmsjXaF6d3W3SeTbX7V:-MmsjXaF6d3W3SeTbX7W:bfu6jme) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/hopannotation/hopannotation.go#L106)):*
> ```Go
> // will terminate when the ctx is cancelled.
> func New(ctx context.Context, annotator ipservice.Client, outputPath string) *HopCache {
> 	if outputPath == "" {
> ```

I associate default value conditions like this with common practice in C++. I think of this as an anti-pattern for Go. Default value logic should be handled by the caller, back up to `main`.

I would call this an anti-pattern because why is only this parameter special? Not in this case, but in general? Why not have the caller specify the value it intends to use? If the value is invalid, fair enough, return an error or nil. But, the caller should provide explicit values. No?
___
*[ipcache/ipcache.go, line 54 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmslf_VDMYrGPbf33Lz:-Mmslf_VDMYrGPbf33M-:b-gisrg8) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/ipcache/ipcache.go#L54)):*
> ```Go
> // goroutine that scrubs the cache.
> func New(ctx context.Context, tracer Tracer, ipCacheTimeout, ipCacheUpdatePeriod time.Duration) *IPCache {
> 	if ipCacheTimeout == 0 {
> ```

Please have the caller provide the correct value. Or, perhaps, if you prefer, eliminate the parameter so that the only source is the flag.
___
*[triggertrace/triggertrace.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-MmsmPivAGwZQn0o-8ZE:-MmsmPivAGwZQn0o-8ZF:bx7cqyk) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L1)):*
> ```Go
> // Package triggertrace triggers a traceroute operation to a destination
> ```

Before I spend too much time, is this a new file or a renamed file? If renamed are there additional edits to the content? It looks like new file and all new content.

If this is a rename, git can track file renames and changes after the rename if the events are committed separately. And these differences can be seen during review to make discerning old/new easier.

**Comment by SaiedKazemi** [comment]
Sounds good, as I'm interested in discussing the subject of default value logic interactively with you. I will email you the list of guides/articles I looked at when deciding an approach that would best fit for our use case.

**Comment by SaiedKazemi** [comment]
___
*[caller.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsib1R7BOTow-8ZE9x:-Mmuazk46M5rl3lKs9iy:b-c2usqj) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/caller.go#L33)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Out of curiosity, why remove `rtx.Must`? This was designed to facilitate unit testing of main and other scenarios where error handling is otherwise fatal. What was clear in one line is now three lines. What is gained by this change?
</blockquote></details>

Because our internal guideline on "Must functions" says that "They should not be used when ordinary error handling is possible".  It's an internal link so I will share it with you separately.  The guideline aside, personally, I find Go's common error checking pattern more readable because, to understand what rtx.Must() does, the reader has to learn the rtx package.

**Comment by SaiedKazemi** [comment]
___
*[hopannotation/hopannotation.go, line 106 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-MmsjXaF6d3W3SeTbX7V:-MmudRNr2KxoaWc6HZRZ:bbeburg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/hopannotation/hopannotation.go#L106)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I associate default value conditions like this with common practice in C++. I think of this as an anti-pattern for Go. Default value logic should be handled by the caller, back up to `main`.

I would call this an anti-pattern because why is only this parameter special? Not in this case, but in general? Why not have the caller specify the value it intends to use? If the value is invalid, fair enough, return an error or nil. But, the caller should provide explicit values. No?

</blockquote></details>

As mentioned earlier, I am interested in an interactive discussion and agree that there may be a better way to handle defaults without introducing complexity in the API.

Whether this is an anti-patter in Go, I don't have a strong opinion.  Perhaps it is but please note that some standard library functions like, ioutil.TEmpDir() and module.DefaultVersion(), check for the empty string in their arguments and use default values -- similar to our use case here.

**Comment by SaiedKazemi** [comment]
___
*[ipcache/ipcache.go, line 54 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmslf_VDMYrGPbf33Lz:-MmuffZ95DJqVhTeh47p:b-y18ys0) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/ipcache/ipcache.go#L54)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please have the caller provide the correct value. Or, perhaps, if you prefer, eliminate the parameter so that the only source is the flag.
</blockquote></details>

Per previous comments, let's discuss.

**Comment by SaiedKazemi** [comment]
___
*[triggertrace/triggertrace.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-MmsmPivAGwZQn0o-8ZE:-MmufobVEsG6-z_jAJgw:b-425j3l) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Before I spend too much time, is this a new file or a renamed file? If renamed are there additional edits to the content? It looks like new file and all new content.

If this is a rename, git can track file renames and changes after the rename if the events are committed separately. And these differences can be seen during review to make discerning old/new easier.
</blockquote></details>

It's a rename via "git mv connectionevent triggertrace" and additional edits to combine the "connection" and "connectionevent" packages into the "triggertrace" package.

**Comment by SaiedKazemi** [comment]
___
*[caller.go, line 39 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsjthd78Kec8n0wRtD:-Mmuh-FnDBSyX29aQyIZ:b-gdv5wx) ([raw file](https://github.com/m-lab/traceroute-caller/blob/61acbe013388ebb3599bc201b89f5bf5f128dc4e/caller.go#L39)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm confused. Why move flags to individual packages?
</blockquote></details>

I noticed that other traceroute-caller packages like ipcache (and now removed connectionpoller) define their own package flags.  Also, outside TRC, packages like ipservice and eventsocket do the same.  So for consistency I moved these to the tracer package.  However, we should actually remove package-level flags because our internal guideline says that "General-purpose packages should be configured using function arguments or global variables, not by punching through to the command-line interface."

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
The organization and naming in triggertrace looks great! Thank you. A few more comments / questions.

> Reviewed 3 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-:-Mn2-yoZCjxfTMYBx7T7:bxljtdv)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

___
*[caller.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsib1R7BOTow-8ZE9x:-Mn1vdUt3zbuQvgpBPJX:b-yt2xzq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/caller.go#L33)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Because our internal guideline on "Must functions" says that "They should not be used when ordinary error handling is possible".  It's an internal link so I will share it with you separately.  The guideline aside, personally, I find Go's common error checking pattern more readable because, to understand what rtx.Must() does, the reader has to learn the rtx package.
</blockquote></details>

We discussed in person. We see things from different perspectives. But, this difference may not matter much.
___
*[caller.go, line 39 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsjthd78Kec8n0wRtD:-Mn1vSsZ8WzY3LLIXfeV:bdnx0x8) ([raw file](https://github.com/m-lab/traceroute-caller/blob/61acbe013388ebb3599bc201b89f5bf5f128dc4e/caller.go#L39)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I noticed that other traceroute-caller packages like ipcache (and now removed connectionpoller) define their own package flags.  Also, outside TRC, packages like ipservice and eventsocket do the same.  So for consistency I moved these to the tracer package.  However, we should actually remove package-level flags because our internal guideline says that "General-purpose packages should be configured using function arguments or global variables, not by punching through to the command-line interface."
</blockquote></details>

We discussed in person, and largely agreed that flags likely belong in main for traceroute-caller packages.
___
*[hopannotation/hopannotation.go, line 106 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-MmsjXaF6d3W3SeTbX7V:-Mn1vkPo1ptDTAxWi4GM:b-yt2xzq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/hopannotation/hopannotation.go#L106)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

As mentioned earlier, I am interested in an interactive discussion and agree that there may be a better way to handle defaults without introducing complexity in the API.

Whether this is an anti-patter in Go, I don't have a strong opinion.  Perhaps it is but please note that some standard library functions like, ioutil.TEmpDir() and module.DefaultVersion(), check for the empty string in their arguments and use default values -- similar to our use case here.
</blockquote></details>

We discussed in person. We see things from different perspectives. But, this difference may not matter much.
___
*[triggertrace/triggertrace.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-MmsmPivAGwZQn0o-8ZE:-Mn1vzb92sFXtstnmSeJ:bq957kn) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L1)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

It's a rename via "git mv connectionevent triggertrace" and additional edits to combine the "connection" and "connectionevent" packages into the "triggertrace" package.
</blockquote></details>

This comes up a lot for myself and others too. I'll see if I can identify the preferable sequence to recommend in the future.
___
*[triggertrace/triggertrace.go, line 82 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mn2-PTUDlB6GzhD4iwM:-Mn2-PTUDlB6GzhD4iwN:bx3u5t) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L82)):*
> ```Go
> 
> 	// TODO(SaiedKazemi): Determine whether the lock can be moved
> 	//     to right before accessing the map.
> ```

It looks safe to me (only references to LocalIPs, no writes). If you determine differently, please let me know - I'd like to see what I didn't see.
___
*[triggertrace/triggertrace.go, line 85 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mn1zXOm6gLD2uyTkP5D:-Mn1zXOm6gLD2uyTkP5E:b-y9wpbi) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L85)):*
> ```Go
> 	h.DestinationsLock.Lock()
> 	defer h.DestinationsLock.Unlock()
> 	destination, err := h.findDestination(*sockID)
> ```

Out of curiosity why dereference the sockID?
___
*[triggertrace/triggertrace.go, line 92 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mn1zhqW1qYvEuqfcneH:-Mn1zhqW1qYvEuqfcneI:blkks6a) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L92)):*
> ```Go
> 	if uuid == "" {
> 		// TODO(SaiedKazemi): Add a metric here.
> 		log.Printf("warning: uuid for SockID %+v is nil\n", *sockID)
> ```

Should this return before falling through? Otherwise the key is the empty string, right?

**Comment by SaiedKazemi** [comment]
___
*[caller.go, line 39 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsjthd78Kec8n0wRtD:-Mn4W9-7DY7pNAQstMQ4:bb8z2tm) ([raw file](https://github.com/m-lab/traceroute-caller/blob/61acbe013388ebb3599bc201b89f5bf5f128dc4e/caller.go#L39)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We discussed in person, and largely agreed that flags likely belong in main for traceroute-caller packages.
</blockquote></details>

I have moved *all* flags to the main package.

**Comment by SaiedKazemi** [comment]
___
*[caller.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsib1R7BOTow-8ZE9x:-Mn4WN6v2okkvv79BGBR:brrtx5j) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/caller.go#L33)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We discussed in person. We see things from different perspectives. But, this difference may not matter much.
</blockquote></details>

Personal perspectives aside, the main blocker for using rtx.Must() is that it calls os.Exit(1), preventing us to test the main() function with invalid arguments.

**Comment by SaiedKazemi** [comment]
___
*[hopannotation/hopannotation.go, line 106 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-MmsjXaF6d3W3SeTbX7V:-Mn4XCEA3rpvYtTcq4iF:bmvy7m4) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/hopannotation/hopannotation.go#L106)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We discussed in person. We see things from different perspectives. But, this difference may not matter much.
</blockquote></details>

I have changed all factory functions to require explicit values.  They do not assume any default values anymore.

**Comment by SaiedKazemi** [comment]
___
*[triggertrace/triggertrace.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-MmsmPivAGwZQn0o-8ZE:-Mn4XxgC3RuHLB_UIwJc:b-7g6cjm) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This comes up a lot for myself and others too. I'll see if I can identify the preferable sequence to recommend in the future.
</blockquote></details>

That would be nice.  I'll be happy to join you and do this together.

**Comment by SaiedKazemi** [comment]
___
*[triggertrace/triggertrace.go, line 82 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mn2-PTUDlB6GzhD4iwM:-Mn4Y7XS61A9gt5vAyo6:b-2gbfei) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L82)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It looks safe to me (only references to LocalIPs, no writes). If you determine differently, please let me know - I'd like to see what I didn't see.
</blockquote></details>

I also think it's safe, but I am keeping it as is in this PR to limit the changes to refactoring the code only (i.e., no application logic changes).

**Comment by SaiedKazemi** [comment]
___
*[triggertrace/triggertrace.go, line 85 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mn1zXOm6gLD2uyTkP5D:-Mn4Zhwo-0Ml9kmHGatY:b-ifd94x) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L85)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Out of curiosity why dereference the sockID?
</blockquote></details>

Because SockID is a pointer and findDestination() takes inetdiag.SockID.  But I changed findDestination() to take a pointer, so there's no need to dereference.

**Comment by SaiedKazemi** [comment]
___
*[triggertrace/triggertrace.go, line 92 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mn1zhqW1qYvEuqfcneH:-Mn4aDmE5LQnfDpjx4hW:b-outl8a) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L92)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should this return before falling through? Otherwise the key is the empty string, right?
</blockquote></details>

The original code didn't even examine uuid.  I was curious if uuid can ever be the empty string and added this if block but I did not want to change the application logic by returning.

**Comment by SaiedKazemi** [comment]
Thank you for your time and feedback.  I hope the refactored code is a lot easier to read, reason about, and maintain.

**Review by stephen-soltesz — APPROVED** [review]
Thank you, @saiedkazemi :lgtm:

> Reviewed 11 of 20 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-:-Mn5ZQd741YlB8IvBfEH:b-i32p2b)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

___
*[caller.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsib1R7BOTow-8ZE9x:-Mn5YBiR40qY11s8PmGC:b-w7l1zl) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/caller.go#L33)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Personal perspectives aside, the main blocker for using rtx.Must() is that it calls os.Exit(1), preventing us to test the main() function with invalid arguments.
</blockquote></details>

How did you work around the call to `os.Exit` with `log.Fatal`? :) 
___
*[triggertrace/triggertrace.go, line 85 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mn1zXOm6gLD2uyTkP5D:-Mn5Yn24E2Eh2YDzddm1:b-8iwgo) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L85)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Because SockID is a pointer and findDestination() takes inetdiag.SockID.  But I changed findDestination() to take a pointer, so there's no need to dereference.
</blockquote></details>

Oh, this is another instance of "no logic changes" in the refactor? Sorry -- it's also just hard to tell what's changed so easier for me to take things as "new" even if they weren't.

**Comment by SaiedKazemi** [comment]
___
*[caller.go, line 33 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mmsib1R7BOTow-8ZE9x:-Mn71SqZDVuVUjdlIEvi:b-r6k2fx) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/caller.go#L33)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How did you work around the call to `os.Exit` with `log.Fatal`? :) 
</blockquote></details>

By introducing the variable `logFatalf` and re-assigning it in `caller_test.go`.  You can see the details in `TestMainWithBadArgs()`.

**Comment by SaiedKazemi** [comment]
___
*[triggertrace/triggertrace.go, line 85 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/127#-Mn1zXOm6gLD2uyTkP5D:-Mn7271NA0qmGu2GLPzx:b-6b8o28) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1b4730beb13779c9292bf7bef9119499fd72c89a/triggertrace/triggertrace.go#L85)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oh, this is another instance of "no logic changes" in the refactor? Sorry -- it's also just hard to tell what's changed so easier for me to take things as "new" even if they weren't.
</blockquote></details>

Yeah, it's confusing even for me sometimes.  In this case, the change was really minor, so effectively there's no application logic change.

**Comment by SaiedKazemi** [comment]
I will merge this set of changes.  The next PR will be for adding the package unit tests.

**Pull request merged**
