### PR TITLE
Use the shx package instead of the pipe package

### PR DESCRIPTION
**Pull request by SaiedKazemi**
The pipe package (gopkg.in/m-lab/pipe.v3) doesn't work as expected
because not only it doesn't support contexts its RunTimeout()
method does not correctly timeout.  As a result, the latency
numbers cannot be trusted.

This commit replaces the pipe package with the shx package in the
ScamperDaemon.trace().	Once we have validated the new code works
as expected, the Scamper.trace() will also use the shx package.

Because there are multiple traces being performed in parallel,
the new code improves log messages by including the context
identifier so individual contexts can be easily identified.

Tested the changes locally using docker-compose.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107)

### CODE REVIEW

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi and @stephen-soltesz)

___
*[tracer/scamper.go, line 229 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Mcv_Bh59nHYC9rG57CQ:-Mcv_Bh59nHYC9rG57CR:b6uyjei) ([raw file](https://github.com/m-lab/traceroute-caller/blob/34e9db503e2e7a649ba83b7736a2debc0409d0cc/tracer/scamper.go#L229)):*
> ```Go
> 	done := make(chan error)
> 	start := time.Now()
> 	var latency float64
> ```

This doesn't need to be declared here.  Local within the case statements is fine.
___
*[tracer/scamper.go, line 236 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Mcv_KHL6dGlUADFElMm:-Mcv_KHL6dGlUADFElMn:b-zedevd) ([raw file](https://github.com/m-lab/traceroute-caller/blob/34e9db503e2e7a649ba83b7736a2debc0409d0cc/tracer/scamper.go#L236)):*
> ```Go
> 	case <-ctx.Done():
> 		latency = time.Since(start).Seconds()
> 		if err = ctx.Err(); err.Error() != "context deadline exceeded" {
> ```

This is much better!

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 229 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Mcv_Bh59nHYC9rG57CQ:-Mcve9bF6lflTdknEMU4:btysaze) ([raw file](https://github.com/m-lab/traceroute-caller/blob/34e9db503e2e7a649ba83b7736a2debc0409d0cc/tracer/scamper.go#L229)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This doesn't need to be declared here.  Local within the case statements is fine.
</blockquote></details>

Yeah, I did the updates differently initially but then moved it inside the case statements.  Removed the declaration.

**Review by SaiedKazemi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[tracer/scamper.go, line 229 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Mcv_Bh59nHYC9rG57CQ:-McvfW4g5j_oB48bek3-:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/34e9db503e2e7a649ba83b7736a2debc0409d0cc/tracer/scamper.go#L229)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Yeah, I did the updates differently initially but then moved it inside the case statements.  Removed the declaration.
</blockquote></details>

Done.

**Review by gfr10598 — COMMENTED** [review]
I manually pushed this to sandbox ndt pods with 45 minute timeout, at around 6:00 am Eastern, and to neubot with 60m timeout, around 7:00 am.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-:-Mcxhvs34w-5h_ifsmox:b647mrt)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

___
*[tracer/scamper.go, line 233 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-McxhOyJ2ErqRHG41zmr:-McxhOyJ2ErqRHG41zms:b-rvipik) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L233)):*
> ```Go
> 	}()
> 	select {
> 	case <-ctx.Done():
> ```

Are these cases necessary?

`cmd.Run()` will return on context cancelled or deadline exceeded. I believe it can be run synchronously.

I believe the error cases can be differentiated using `if errors.Is(err, context.DeadlineExceeded) {...}` rather than string comparison.

So, I see a need for only three cases:

* err is nil
* err is context.DeadlineExceeded
* err is not nil otherwise

Can the current logic be simplified?

**Review by gfr10598 — COMMENTED** [review]
I've made branch gfr-shx, which uses simple shx.Exec, and manually pushed it to the sandbox host pods, with 90m timeout.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-:-Mcxj362CsW_iM6p35Cg:b-z8bk91)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

**Review by gfr10598 — COMMENTED** [review]
Looks like the -O json option does not work with scamper-daemon, so I'm reverting the host pods to use sandbox-saied-trace again, but keeping the 90 minute timeout, to get more data about long running traces.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-:-Mcxkm6KCxrKJNKPMuzn:bfyc6pc)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

**Review by gfr10598 — COMMENTED** [review]
After ndt pods ran for a couple hours, it is apparent that the majority of traces (in sandbox ndt) are taking 45 minutes or more.  The host and neubot pods have much shorter typical trace times. 

Changing ndt pods to 2h timeout, so we can see what the typical time for successful traces looks like.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-:-McxyrWiAQZfscP8NIzv:baisq78)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-:-McxzrfwCbOkHeoa7u0F:blpfx18)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

**Review by gfr10598 — COMMENTED** [review]
I've added gfr-params branch, which currently adds -w 2 parameter to change the wait time between probes.  It is otherwise identical to this branch.  Deployed to ndt sandbox pods at 8:45 Eastern

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-:-Mcy2hNQ5P8jRjPsXxVq:b-wig83k)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

**Review by gfr10598 — COMMENTED** [review]
Looks like the -w 2 parameter caused crash looping.  Looks like actually the build failed, so it is odd that we see crash looping instead of Image Fetch Backoff.   Investigating.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-:-Mcy6xBy5DnpYcj7FviV:b-npm4g7)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

**Review by gfr10598 — COMMENTED** [review]
It was a stray extra param that was causing the problem.  Fixed, and now seems to greatly reduce the rate at which the number of concurrent traces grows in sandbox ndt pod.

To move this along, I'm going to work on additional changes suggested by soltesz, on the gfr-params branch, and we can cherrypick them if they make sense.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-:-McyY43xDbelFxtOWvc7:b-g2s85k)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @SaiedKazemi)

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107)* status: 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[tracer/scamper.go, line 233 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-McxhOyJ2ErqRHG41zmr:-Mcyb6U77jS49ivbgbH5:b661j9u) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L233)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are these cases necessary?

`cmd.Run()` will return on context cancelled or deadline exceeded. I believe it can be run synchronously.

I believe the error cases can be differentiated using `if errors.Is(err, context.DeadlineExceeded) {...}` rather than string comparison.

So, I see a need for only three cases:

* err is nil
* err is context.DeadlineExceeded
* err is not nil otherwise

Can the current logic be simplified?
</blockquote></details>

I'm trying this in gfr-params, and will push it to host pods to test.

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107)* status: 0 of 1 approvals obtained (waiting on @gfr10598, @SaiedKazemi, and @stephen-soltesz)

___
*[tracer/scamper.go, line 219 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-MczDRLK1NX-CQ2T5Pyu:-MczDRLK1NX-CQ2T5Pyv:b-4184id) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L219)):*
> ```Go
> 	filename := dir + d.generateFilename(conn.Cookie, t)
> 	log.Printf("Starting a trace to be put in %s (context %p)", filename, ctx)
> 	tracelbCmd := []string{"tracelb", "-P", "icmp-echo", "-q", "3", "-O", "ptr", conn.RemoteIP}
> ```

Add "-w", "2" which seems to make a big difference.
___
*[tracer/scamper.go, line 219 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-MczDZ3MCLztWyIXt45w:-MczDZ3MCLztWyIXt45x:b-jt2mgv) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L219)):*
> ```Go
> 	filename := dir + d.generateFilename(conn.Cookie, t)
> 	log.Printf("Starting a trace to be put in %s (context %p)", filename, ctx)
> 	tracelbCmd := []string{"tracelb", "-P", "icmp-echo", "-q", "3", "-O", "ptr", conn.RemoteIP}
> ```

We'll try dropping the -O ptr.
___
*[tracer/scamper.go, line 219 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-MczDcskAxgoIEqetWRv:-MczDcskAxgoIEqetWRw:b-uxvpit) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L219)):*
> ```Go
> 	filename := dir + d.generateFilename(conn.Cookie, t)
> 	log.Printf("Starting a trace to be put in %s (context %p)", filename, ctx)
> 	tracelbCmd := []string{"tracelb", "-P", "icmp-echo", "-q", "3", "-O", "ptr", conn.RemoteIP}
> ```

We should also test in sandbox with 1h timeout, 10 minute IPCacheTimeout, and 1 minute IPCache...Period.  If these work well, then we should merge and deploy to staging.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 219 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-MczDRLK1NX-CQ2T5Pyu:-Md-C3sQAipMJG-YT27D:b4md3i4) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L219)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add "-w", "2" which seems to make a big difference.
</blockquote></details>

It's actually "-W" (capital W) which is specifies in 1/100ths of seconds how long to wait between probes.  I've added support to specify this via a flag.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 219 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-MczDZ3MCLztWyIXt45w:-Md-CVNk92boGzxX4Nb5:b-vstyma) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L219)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

We'll try dropping the -O ptr.
</blockquote></details>

I've added a flag to include/exclude "-O ptr" in tracelb command.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 219 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-MczDcskAxgoIEqetWRv:-Md-CcjMDPXLSlFyUMRj:b-u2zqjd) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L219)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

We should also test in sandbox with 1h timeout, 10 minute IPCacheTimeout, and 1 minute IPCache...Period.  If these work well, then we should merge and deploy to staging.
</blockquote></details>

I modified docker-compose.yaml to use the above values.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 219 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-MczDRLK1NX-CQ2T5Pyu:-Md-D5tN1_DOnlD6gVTA:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L219)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

It's actually "-W" (capital W) which is specifies in 1/100ths of seconds how long to wait between probes.  I've added support to specify this via a flag.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 219 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-MczDZ3MCLztWyIXt45w:-Md-D7nx55m4cAZt5zgU:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L219)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I've added a flag to include/exclude "-O ptr" in tracelb command.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 219 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-MczDcskAxgoIEqetWRv:-Md-D9DS5iQPrX8TyTws:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L219)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I modified docker-compose.yaml to use the above values.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 233 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-McxhOyJ2ErqRHG41zmr:-Md-DGtI9xw573-0GYxZ:bf67aj7) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L233)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I'm trying this in gfr-params, and will push it to host pods to test.
</blockquote></details>

Thank you @stephen-soltesz for your suggestion.  I have simplified the code.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 233 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-McxhOyJ2ErqRHG41zmr:-Md-DSTE1h8ROh6UyQqD:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/7f7edd3e30b47b92757199e6ec56080f4f004bad/tracer/scamper.go#L233)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Thank you @stephen-soltesz for your suggestion.  I have simplified the code.
</blockquote></details>

Done.

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi and @stephen-soltesz)

___
*[caller.go, line 55 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-Ect31ZufrORH2bCr:-Md-Ect31ZufrORH2bCs:bq2g10u) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/caller.go#L55)):*
> ```Go
> 	scamperCtrlSocket = flag.String("scamper.unixsocket", "/tmp/scamperctrl", "The name of the UNIX-domain socket that the scamper daemon should listen on.")
> 	scamperTimeout    = flag.Duration("scamper.timeout", 900*time.Second, "How long to wait to complete a scamper trace.")
> 	scamperNoPTR      = flag.Bool("scamper.tracelb-no-ptr", false, "Do not look up DNS pointer records for IP addresses.")
> ```

Reverse this to scamperWithPTR, and default to true.  Otherwise double negatives = confusing
___
*[tracer/scamper.go, line 116 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-FDf53XIVE7DjQb8-:-Md-FDf53XIVE7DjQb80:bw9gowl) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L116)):*
> ```Go
> 
> 	// Now run the command.
> 	log.Printf("Starting a trace to save in %s (context %p)", filename, ctx)
> ```

Please choose one or the other of these, to reduce spam.  I prefer the second one, as it is more helpful for debugging.
___
*[tracer/scamper.go, line 134 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-FKwKD2teEf2Sq142:-Md-FKwKD2teEf2Sq143:b17tx6v) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L134)):*
> ```Go
> 		fmt.Printf("Trace failed in context %p (error: %v)\n", ctx, err)
> 	} else {
> 		log.Printf("Trace succeeded in context %p\n", ctx)
> ```

Suggest you delete this log, to reduce spam.
___
*[tracer/scamper.go, line 230 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-FWtU4ezsWjImu30P:-Md-FWtU4ezsWjImu30Q:b-b118wo) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L230)):*
> ```Go
> }
> 
> // TODO: The common code in trace() methods should be placed in a
> ```

I was just about to write this as a comment.  8-)

**Review by gfr10598 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-:-Md-G6EC6Khmdf-aSYGN:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi and @stephen-soltesz)

___
*[tracer/scamper.go, line 270 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-G2_p6psiPBtm-d_X:-Md-G2_p6psiPBtm-d_Y:b-xdp8hp) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L270)):*
> ```Go
> 		traceTimeHistogram.WithLabelValues("error").Observe(latency)
> 		if errors.Is(ctx.Err(), context.DeadlineExceeded) {
> 			log.Printf("Trace timed out in context %p after %v\n", ctx, d.ScamperTimeout)
> ```

Is this what you want?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[tracer/scamper.go, line 132 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-KFUmANPjJDnDETbj:-Md-KFUmANPjJDnDETbk:b-a5h0c9) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L132)):*
> ```Go
> 			return "", err
> 		}
> 		fmt.Printf("Trace failed in context %p (error: %v)\n", ctx, err)
> ```

nit: do not mix `fmt` and `log` output.
___
*[tracer/scamper.go, line 276 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-KC8ZDKPg3nECmGqz:-Md-KC8ZDKPg3nECmGr-:b-a5h0c9) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L276)):*
> ```Go
> 			return "", err
> 		}
> 		fmt.Printf("Trace failed in context %p (error: %v)\n", ctx, err)
> ```

nit: do not mix `fmt` and `log` output.
___
*[tracer/scamper.go, line 285 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-Jq7R6cycZiD4R_G3:-Md-Jq7R6cycZiD4R_G4:b2hsi99) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L285)):*
> ```Go
> 	// error, the output won't be complete but we write whatever we have
> 	// instead of discarding it.
> 	rtx.PanicOnError(ioutil.WriteFile(filename, buff.Bytes(), 0666), "Could not save output to file")
> ```

Previously, non-nil errors would not write files. Now there are non-timeout errors that will still write the content of buff to a file.

This is new behavior. Is this intended?
___
*[tracer/scamper_test.go, line 243 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-KTeAB9m14pSYL2Ym:-Md-KTeAB9m14pSYL2Yn:bqyujd5) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper_test.go#L243)):*
> ```Go
> 	prometheusx.GitShortCommit = "Fake Version"
> 	data, err := d.Trace(c, faketime)
> 	if err.Error() != "context deadline exceeded" {
> ```

Prefer `errors.Is()` over string comparisons when possible.

**Comment by SaiedKazemi** [comment]
___
*[caller.go, line 55 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-Ect31ZufrORH2bCr:-Md-Y-Hg7AdHV1uHsC8s:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/caller.go#L55)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Reverse this to scamperWithPTR, and default to true.  Otherwise double negatives = confusing
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 116 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-FDf53XIVE7DjQb8-:-Md-YCPB6fHqvlNfCg41:b-ua4zz2) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L116)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please choose one or the other of these, to reduce spam.  I prefer the second one, as it is more helpful for debugging.
</blockquote></details>

I kept the first one ("Starting a trace ...") for backward compatibility, but I will merge them into one and make it consistent with other messages (i.e., Trace {started,timed out,failed,succeeded} in context...).

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 132 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-KFUmANPjJDnDETbj:-Md-a4Vf4NYz1FDCjHCs:b-yb74t1) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L132)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: do not mix `fmt` and `log` output.
</blockquote></details>

That was an oversight.  Thanks for catching it.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 134 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-FKwKD2teEf2Sq142:-Md-aCQKDMk7fZkZs3NF:bnqdvvq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L134)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Suggest you delete this log, to reduce spam.
</blockquote></details>

This short message helps parsers to easily determine status of traces explicitly as opposed to implicitly assuming success in the absence of any error messages.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 230 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-FWtU4ezsWjImu30P:-Md-az203zBrdlyDr5QM:b-dykkfg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L230)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I was just about to write this as a comment.  8-)
</blockquote></details>

Will do this in the next round of code clean ups and improvements.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 270 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-G2_p6psiPBtm-d_X:-Md-bE8I74I_DhCYDnpB:bohyhl0) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L270)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is this what you want?
</blockquote></details>

By "this" I assume you mean `return "", err'.  As the comment says, test code expects null output when a trace times out.  I will change the test code to accept partial output because we want to save whatever output we had before the trace timed out.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 285 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-Jq7R6cycZiD4R_G3:-Md-c79F7rg0iRG3kjpN:bcues8h) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L285)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Previously, non-nil errors would not write files. Now there are non-timeout errors that will still write the content of buff to a file.

This is new behavior. Is this intended?

</blockquote></details>

Yes, the new behavior is intended.  If a traceroute times out on, say, hop number 12, the data that we have for the first 11 hops is still useful.  That said, I need to verify that scamper does provide partial output when a traceroute times out.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper_test.go, line 243 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-KTeAB9m14pSYL2Ym:-Md-dK1B3oWvU1E10na5:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper_test.go#L243)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Prefer `errors.Is()` over string comparisons when possible.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[caller.go, line 55 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-Ect31ZufrORH2bCr:-Md-dVKp4XC34_VDVSCs:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/caller.go#L55)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 285 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-Jq7R6cycZiD4R_G3:-Md-d_Rb3rfGqPtFhHqM:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L285)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Yes, the new behavior is intended.  If a traceroute times out on, say, hop number 12, the data that we have for the first 11 hops is still useful.  That said, I need to verify that scamper does provide partial output when a traceroute times out.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
@gfr10598, please merge if you and @stephen-soltesz are OK.  Obviously, we will continue to iteratively make further improvements.

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/107)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi and @stephen-soltesz)

___
*[tracer/scamper.go, line 134 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-FKwKD2teEf2Sq142:-Md3Zq12ATOuBR3kz1Bx:b-a37ix1) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L134)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

This short message helps parsers to easily determine status of traces explicitly as opposed to implicitly assuming success in the absence of any error messages.
</blockquote></details>

Ok for now, but our logs are actually huge, and this is more appropriate for a metric rather than a log.
___
*[tracer/scamper.go, line 270 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-G2_p6psiPBtm-d_X:-Md3_EoC71yc7wR3HDUh:b1c7ign) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L270)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

By "this" I assume you mean `return "", err'.  As the comment says, test code expects null output when a trace times out.  I will change the test code to accept partial output because we want to save whatever output we had before the trace timed out.
</blockquote></details>

Yes that is what I meant.
___
*[tracer/scamper.go, line 285 at r4](https://reviewable.io/reviews/m-lab/traceroute-caller/107#-Md-Jq7R6cycZiD4R_G3:-Md3_nAI4VgNk7BenqXx:b-v2wvsj) ([raw file](https://github.com/m-lab/traceroute-caller/blob/bc13d3aecc136c2df475ceedaaad52d2eda9d27c/tracer/scamper.go#L285)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We also need to determine whether scamper actually returns anything useful when it errors.  If we do end up writing files for errored traces, I think we also need to add information to the metadata line to indicate that.

**Pull request merged**
