### PR TITLE
Now tests non-stalling of races.

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/45)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/45)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @pboothe)

___
*[ipcache/ipcache_test.go, line 94 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGfkaw7Q9d22U6HkBd:-LvGfkax8u_JlKram8SL:b-dl735q) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L94)):*
> ```Go
> }
> 
> type testPausingTracer struct {
> ```

nit: I am guilty of this too.  I think we would do better not to use the "test" prefix on lots of things in test modules.  Wouldn't just pausingTracer be sufficient in this context?
___
*[ipcache/ipcache_test.go, line 102 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGg4Hq8JeLqdfy6J9O:-LvGg4HrAktbDzhPNLAm:b-1y0bxw) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L102)):*
> ```Go
> 
> func (tpt *testPausingTracer) Trace(conn connection.Connection, t time.Time) string {
> 	time.Sleep(1 * time.Millisecond)
> ```

I think this should be duration(rand.intn(1000000)) rather than a fixed time.
___
*[ipcache/ipcache_test.go, line 106 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGgImR7vpYBqAp316f:-LvGgImS9k1nP6ZHcySP:btza1q5) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L106)):*
> ```Go
> 		<-tpt.ctx.Done()
> 	}
> 	tpt.mut.Lock()
> ```

This may cause incidental synchronization and possibly hide other concurrency bugs.  If you really need a counter in the tracer, use an atomic, which is not ideal, but it is better.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/45)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @pboothe)

___
*[ipcache/ipcache_test.go, line 102 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGg4Hq8JeLqdfy6J9O:-LvGqFZI3MM20rNptbQs:b-q2nf7g) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L102)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this should be duration(rand.intn(1000000)) rather than a fixed time.
</blockquote></details>

Ah - this is fine, but add a random delay inside the lock.
___
*[ipcache/ipcache_test.go, line 114 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGqLRZ2WZSYffUFz3N:-LvGqLRZ2WZSYffUFz3O:byjethn) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L114)):*
> ```Go
> func (tpt *testPausingTracer) CreateCacheTest(conn connection.Connection, t time.Time, cachedTest string) {
> 	tpt.mut.Lock()
> 	tpt.successes++
> ```

Add a short random delay here.
___
*[ipcache/ipcache_test.go, line 125 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGqZO19pz6PBNuXa_k:-LvGqZO19pz6PBNuXa_l:bpexxz1) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L125)):*
> ```Go
> 		traceToBlock: "77",
> 	}
> 	c := ipcache.New(ctx, tpt, 100*time.Second, 10*time.Second)
> ```

Ah - can we make it do GC as well by setting a very short GC interval?
___
*[ipcache/ipcache_test.go, line 134 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGrP9a1_SswehKizuz:-LvGrP9a1_SswehKizv-:bn9ehcz) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L134)):*
> ```Go
> 	for i := 0; i < 1000; i++ {
> 		go func(j int) {
> 			if s := c.Trace(connection.Connection{RemoteIP: fmt.Sprintf("%d", j)}); s != fmt.Sprintf("Trace to %d", j) {
> ```

Add a small random delay before Trace()

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/45)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[ipcache/ipcache_test.go, line 104 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGs8drCanpv_hGdadG:-LvGs8drCanpv_hGdadH:b-j8rgjg) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L104)):*
> ```Go
> 	time.Sleep(1 * time.Millisecond)
> 	if conn.RemoteIP == tpt.traceToBlock {
> 		<-tpt.ctx.Done()
> ```

This is blocking outside the lock, and always on the same request, so I'm not sure what it actually accomplishes.  I misunderstood when we discussed this morning.

**Review by gfr10598 — COMMENTED** [review]
:lgtm:  After adding random delays inside locks, using atomic counter.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-:-LvGtXMT-jcxICFM-rE-:b-hy3kdm)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/45)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[ipcache/ipcache_test.go, line 124 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGvIiCC3LcYz6Io_a8:-LvGvIiCC3LcYz6Io_a9:b-273eba) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1ed9743ce8389ca90891498171e5904e2168610a/ipcache/ipcache_test.go#L124)):*
> ```Go
> 		traceToBlock: "77",
> 	}
> 	c := ipcache.New(ctx, pt, 1*time.Millisecond, 1*time.Microsecond)
> ```

I think this needs to be less than the random delay if you want to be assured something gets GC'd. 

IIUC, the entire test can possibly complete in roughly three delay times - one before calling trace, one for the initial test creation, and one for all the other calls to Trace to complete in parallel?  So maybe set the GC to the expected value of the random delay?
___
*[ipcache/ipcache_test.go, line 133 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGuKj13fxxAndN6dwB:-LvGuKj13fxxAndN6dwC:br30kse) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1ed9743ce8389ca90891498171e5904e2168610a/ipcache/ipcache_test.go#L133)):*
> ```
> 000
> ```
This is  10milliseconds, which is probably too long.  Actually, probably good to make all the delays O(100 microseconds), but at least make them all the same.  A good option would be to use a single randomDelay() function everywhere.

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/45)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[ipcache/ipcache_test.go, line 125 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGqZO19pz6PBNuXa_k:-LvHaa1T1Aim2gPD-UNK:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L125)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Ah - can we make it do GC as well by setting a very short GC interval?
</blockquote></details>

Done.
___
*[ipcache/ipcache_test.go, line 134 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGrP9a1_SswehKizuz:-LvHaaZD7083p2-84rm2:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/e3106a92dd10ae56198d71d36a175d04d6325dfc/ipcache/ipcache_test.go#L134)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add a small random delay before Trace()
</blockquote></details>

Done.
___
*[ipcache/ipcache_test.go, line 124 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGvIiCC3LcYz6Io_a8:-LvHaa9r4wy1wfcYclcH:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1ed9743ce8389ca90891498171e5904e2168610a/ipcache/ipcache_test.go#L124)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this needs to be less than the random delay if you want to be assured something gets GC'd. 

IIUC, the entire test can possibly complete in roughly three delay times - one before calling trace, one for the initial test creation, and one for all the other calls to Trace to complete in parallel?  So maybe set the GC to the expected value of the random delay?

</blockquote></details>

Done.
___
*[ipcache/ipcache_test.go, line 133 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-LvGuKj13fxxAndN6dwB:-LvHaaKC08ibSUEhQJsv:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/1ed9743ce8389ca90891498171e5904e2168610a/ipcache/ipcache_test.go#L133)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

> ```
> 000
> ```
This is  10milliseconds, which is probably too long.  Actually, probably good to make all the delays O(100 microseconds), but at least make them all the same.  A good option would be to use a single randomDelay() function everywhere.
</blockquote></details>

Done.

**Review by gfr10598 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/45#-:-LvHajMTCXT7H5Q3V0IZ:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/traceroute-caller/issues/38

**Pull request merged**
