### PR TITLE
add schema for PT test raw.

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/74)

### CODE REVIEW

**Review by pboothe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/74)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[schema/schema.go, line 32 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/74#-M6jrujzABUuTO1u-aWM:-M6jrujzABUuTO1u-aWN:b-us6zto) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ffc49ecacd09690bb423d2ae3e5076ea31b8b974/schema/schema.go#L32)):*
> ```Go
> }
> 
> type PTTestRaw struct {
> ```

Need a `Version string` field to indicate the schema version. Right now it would always be 1.
___
*[schema/schema.go, line 43 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/74#-M6jrnBO5BJnAKCxZu4V:-M6jrnBP2hanm7aeIKCl:b-sf3fc6) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ffc49ecacd09690bb423d2ae3e5076ea31b8b974/schema/schema.go#L43)):*
> ```Go
> 	ProbeC         int64        `json:"probec,int64"`
> 	Hop            []ScamperHop `json:"hop"`
> 	ExpVersion     string       `json:"exp_version,string" bigquery:"exp_version"`
> ```

What is "ExpVersion"?  The version of Scamper? The version of the traceroute-caller binary?  Also, there's a function that get's a version that is no longer called in tests. Does the output of that go here?

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/74)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[schema/schema.go, line 43 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/74#-M6jrnBO5BJnAKCxZu4V:-M6k3HC0EVwPragI1XFl:bp9u1mw) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ffc49ecacd09690bb423d2ae3e5076ea31b8b974/schema/schema.go#L43)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

What is "ExpVersion"?  The version of Scamper? The version of the traceroute-caller binary?  Also, there's a function that get's a version that is no longer called in tests. Does the output of that go here?
</blockquote></details>

ScamperVersion is the version of scamper binary, parsed from output of scamper.

It is parsed from tracelb line, such as

{"type":"tracelb", "version":"0.1", .......

ExpVersion is TracerouteCaller version, parsed from the meta line of previous .jsonl output

One sample meta line form .jsonl file:

{"UUID":"ndt-plh7v_1566050090_000000000004D60F","TracerouteCallerVersion":"bc092be","CachedResult":true,"CachedUUID":"ndt-w6lxg_1565921414_00000000000038C0"}

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/74)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[schema/schema.go, line 32 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/74#-M6jrujzABUuTO1u-aWM:-M6k5bikDDCW_2BfaOAv:b-98j03p) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ffc49ecacd09690bb423d2ae3e5076ea31b8b974/schema/schema.go#L32)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Need a `Version string` field to indicate the schema version. Right now it would always be 1.
</blockquote></details>

So this version is just fro PTTestRaw?

In the future, when I define the new PTTest Schema, like

type PTTest struct {
   A PTSummary bigquery:"a"
   Server annotator.ServerAnnotations bigquery:"server"
   Client annotator.ClientAnnotations bigquery:"client"
   ParseInfo ParseInfo bigquery:"parseInfo"
   TestTime time.Time bigquery:"testTime"
   Raw PTTestRaw bigquery:"raw"
   Version string (???)
}

Do I need to have a version there as well?

**Review by pboothe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/74)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[schema/schema.go, line 32 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/74#-M6jrujzABUuTO1u-aWM:-M6kE5BL5C4mm5wNDt7S:bgyoatc) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ffc49ecacd09690bb423d2ae3e5076ea31b8b974/schema/schema.go#L32)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

So this version is just fro PTTestRaw?

In the future, when I define the new PTTest Schema, like

type PTTest struct {
   A PTSummary bigquery:"a"
   Server annotator.ServerAnnotations bigquery:"server"
   Client annotator.ClientAnnotations bigquery:"client"
   ParseInfo ParseInfo bigquery:"parseInfo"
   TestTime time.Time bigquery:"testTime"
   Raw PTTestRaw bigquery:"raw"
   Version string (???)
}

Do I need to have a version there as well?
</blockquote></details>

The schema saved to disk needs to be versioned.  It is quite likely that the Version field that etl creates will be derived from this Version field.  If you want, you could call this field `SchemaVersion` instead of just `Version`, because you are also saving versions for scamper and traceroute-caler.
___
*[schema/schema.go, line 43 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/74#-M6jrnBO5BJnAKCxZu4V:-M6kEQAR4Uyuen5l8B6P:b-t873ps) ([raw file](https://github.com/m-lab/traceroute-caller/blob/ffc49ecacd09690bb423d2ae3e5076ea31b8b974/schema/schema.go#L43)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

ScamperVersion is the version of scamper binary, parsed from output of scamper.

It is parsed from tracelb line, such as

{"type":"tracelb", "version":"0.1", .......

ExpVersion is TracerouteCaller version, parsed from the meta line of previous .jsonl output

One sample meta line form .jsonl file:

{"UUID":"ndt-plh7v_1566050090_000000000004D60F","TracerouteCallerVersion":"bc092be","CachedResult":true,"CachedUUID":"ndt-w6lxg_1565921414_00000000000038C0"}


</blockquote></details>

No need to parse it from the meta line. It is saved as a global variable: https://github.com/m-lab/go/blob/master/prometheusx/prom.go#L31 `prometheusx.GitShortCommit`

If it is the current commit of traceroute caller, then please use the name TracerouteCallerCommit. ExpVersion is ambiguous.

**Review by pboothe — APPROVED** [review]
Once https://coveralls.io/builds/30634098/source?filename=parser/pt.go#L44 is either covered by tests or the entire function is deleted: LGTM 

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/74#-:-M6kUwm19HGo4XuVfyFv:be1vgwv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @yachang)

**Pull request merged**
