### PR TITLE
Apply anonymization to traces before writing in triggertrace

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds anonymization to the triggertrace handler before of writing trace output. To perform this, this change includes two new methods to the parser interface for `Scamper1` and `Scamper2` types that `Anonymize()` the parsed data and `MarshalJSONL` to return the parsed data back to a `[]byte` for saving.

This is the second of two PRs to add anonymization support to the traceroute-caller.
* https://github.com/m-lab/traceroute-caller/pull/151

This change depends on https://github.com/m-lab/go/pull/153 - PR is a draft until that change is merged.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/154)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
@SaiedKazemi this isn't ready for detailed review - but I wanted to share with you to see the shape of things, in case you had early feedback.

**Comment by SaiedKazemi** [comment]
*[`parser/scamper1_test.go` line 42 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/154#-NL1hcKx2-x6RrLSm-3j:-NL1hcKx2-x6RrLSm-3k:b-9q51mp) ([raw file](https://github.com/m-lab/traceroute-caller/blob/189c0c7357dc02d96a80780dd34001c6128e69e7/parser/scamper1_test.go#L42)):*
> ```Go
> 		// Read in the test traceroute output file.
> 		f := filepath.Join("./testdata/scamper1", test.file)
> 		t.Logf("\nTest %v: file: %v", i, f)
> ```

Not sure why this line had to be removed?  It makes the logs easier to read in verbose mode.

**Comment by SaiedKazemi** [comment]
*[`parser/scamper1_test.go` line 42 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/154#-NL1hcKx2-x6RrLSm-3j:-NL1jCDR574LowOMEGrH:b2ub421) ([raw file](https://github.com/m-lab/traceroute-caller/blob/189c0c7357dc02d96a80780dd34001c6128e69e7/parser/scamper1_test.go#L42)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Not sure why this line had to be removed?  It makes the logs easier to read in verbose mode.
</blockquote></details>

Never mind the comment; I see you are using t.Run().

**Review by SaiedKazemi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/154#-:-NL1jjL-BivaAqLmgXc1:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by SaiedKazemi** [comment]
@stephen-soltesz I know this PR isn't ready and you sent it to me for early comments (if any).  My LGTM means no major comments so far.

**Review by stephen-soltesz — COMMENTED** [review]
@saiedkazemi this PR is now ready for review. There is room for more testing of the trigger trace handler but the current PR is getting large.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/154#-:-NL2nuKD3uFcesWUBlLu:baaw1gy)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

**Comment by SaiedKazemi** [comment]
:lgtm:

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/154)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Thank you!

**Comment by stephen-soltesz** [comment]
I've verified locally that this works as intended for IPv4. I'll merge this PR and add a new test with a fakeTracer that produces a static result and verifies the result is anonymized correctly. After that I think it would be safe to use in production where needed.

**Pull request merged**
