### PR TITLE
Cleanup and add support for sc_attach

### PR DESCRIPTION
**Pull request by pboothe**
Begin the productionization process for this repo.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10)

### CODE REVIEW

**Review by yachang — COMMENTED** [review]
Thanks a lot for doing this!
Did you try to build a new Docker image using this PR, and run it on sandbox? 

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-:-LbZRl9_9zMURRHJQ236:b-yq77gh)* status: 0 of 1 approvals obtained (waiting on @yachang)

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[.travis.yml, line 6 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-LbxY0roAprNIhcpDSjA:-LbxY0rpCxWOcmjwLGCL:bl5g136) ([raw file](https://github.com/m-lab/traceroute-caller/blob/47c38ed47e6ce389412dcd70f5062aadacaecd86/.travis.yml#L6)):*
> ```YAML
> - go get github.com/mattn/goveralls
> # Install dependencies, including test dependencies.
> - go get -v -t ./...
> ```

Add that prometheusx short commit version thing. Thanks!

**Comment by pboothe** [comment]
Also addresses https://github.com/m-lab/dev-tracker/issues/224

**Comment by pboothe** [comment]
Fixes https://github.com/m-lab/dev-tracker/issues/197

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[caller.go, line 22 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-Lc1m_2g4gc1oIK5gX-O:-Lc1m_2g4gc1oIK5gX-P:b-9r28ma) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0cbe59e53c15e72cdfa6266bd4563aa8c330649d/caller.go#L22)):*
> ```
> /tmp/scamperctrl
> ```
___
*[scamper/scamper.go, line 39 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-Lc1nE2wAMWZgp8ZepEW:-Lc1nE2wAMWZgp8ZepEX:bphjrin) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0cbe59e53c15e72cdfa6266bd4563aa8c330649d/scamper/scamper.go#L39)):*
> ```Go
> 	go func() {
> 		err := command.Wait()
> 		log.Printf("Scamper exited with error: %v\n", err)
> ```

Just log.Printf(), should send a warning, or something more severe

**Review by yachang — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe)

___
*[scamper/scamper.go, line 64 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-Lc1zXleAHcMBD6QuWA7:-Lc1zXlf7WBZf5o8tbFt:bcrc1kh) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0cbe59e53c15e72cdfa6266bd4563aa8c330649d/scamper/scamper.go#L64)):*
> ```Go
> 	uuid, err := conn.UUID()
> 	rtx.Must(err, "Could not create UUID from connection - this should never happen")
> 	filename := filepath + "/" + uuid + ".json"
> ```

The uuid used to be inside file, but not in filename. Do you want to change it?

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @pboothe and @yachang)

___
*[.travis.yml, line 6 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-LbxY0roAprNIhcpDSjA:-LbypKRg9ILfecfvMzkW:bkm5bns) ([raw file](https://github.com/m-lab/traceroute-caller/blob/47c38ed47e6ce389412dcd70f5062aadacaecd86/.travis.yml#L6)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add that prometheusx short commit version thing. Thanks! 
</blockquote></details>

Done (in the docker file)
___
*[caller.go, line 22 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-Lc1m_2g4gc1oIK5gX-O:-Lc2I8fk3yi48tBg8tWe:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0cbe59e53c15e72cdfa6266bd4563aa8c330649d/caller.go#L22)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

> ```
> /tmp/scamperctrl
> ```

</blockquote></details>

Done.

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

___
*[scamper/scamper.go, line 64 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-Lc1zXleAHcMBD6QuWA7:-Lc2IAuqClIbsSwImE4z:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/0cbe59e53c15e72cdfa6266bd4563aa8c330649d/scamper/scamper.go#L64)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

The uuid used to be inside file, but not in filename. Do you want to change it?
</blockquote></details>

Done.

**Review by pboothe — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-:-Lc2ICNM6ppOpybLOszO:bb71pro)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

**Review by yachang — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-:-Lc2YVb47RPL5SsKvfEX:bg7igkv)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @yachang)

**Review by yachang — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/10#-:-Lc2YXzUD5no-fxVjx-z:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @yachang)

**Pull request merged**
