### PR TITLE
Extract start time, tracelb line, and hops from traceroute output

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit adds the following exported functions to the parser
in preparation for adding support for hopannotation1 datatype.
It also refactors package testing code to follow Go conventions.

    ExtractStartTime()
    ExtractTraceLB()
    ExtractHops()

The changes were tested via "go test" with 100% coverage and
also with "docker-compose" on local workstation.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/118)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/118)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[parser/json.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ12gm4G-VkrTAS3Cq:-MhQ12gm4G-VkrTAS3Cr:b-opbt6n) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L1)):*
> ```Go
> // Package parser handles parsing of scamper JSONL.
> ```

The filename should not be json.go.  Can you change it to something more meaningful?
___
*[parser/json.go, line 131 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1EuA742MQXUTVi1t:-MhQ1EuB9W093OAVPe_Z:b9ruiny) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L131)):*
> ```Go
> 
> // ExtractStartTime extracts the "start_time" field of the "cycle-start"
> // line from scamper JSONL output.
> ```

I don't think any of these should be exported.  Can you change them, and use export_test.go to make them available for unit tests?
___
*[parser/json.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1ZT_87dyuJqIn2BG:-MhQ1ZT_87dyuJqIn2BH:b-q1tjjb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L165)):*
> ```Go
> 	var cycleStop CyclestopLine
> 
> 	jsonStrings := strings.Split(strings.TrimSpace(string(data)), "\n")
> ```

In the alternate parser code we were playing with, I separated out the split and 4 line check.  Since there is duplicate code here, I suggest you pull out code that separates the 4 lines and puts the raw data into 4 fields in an unexported datatype.  Then you can implement these extract functions on that datatype instead of passing in []byte.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/118)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[parser/json.go, line 87 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ2EJh5XnCcj9xnO3u:-MhQ2EJh5XnCcj9xnO3v:bmoojf9) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L87)):*
> ```Go
> 
> // CyclestartLine contains the information about the scamper "cyclestart"
> type CyclestartLine struct {
> ```

We probably should consider whether these structs even need to be exported.

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 1 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ12gm4G-VkrTAS3Cq:-MhQF7MEAVjKfgVRobrG:b-q8by1o) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

The filename should not be json.go.  Can you change it to something more meaningful?
</blockquote></details>

Changed the names to scamper_output.go and scamper_output_test.go because these files parse scamper output.

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 87 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ2EJh5XnCcj9xnO3u:-MhQFvAYDo3wefogxNtc:b-1owdr7) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L87)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

We probably should consider whether these structs even need to be exported. 
</blockquote></details>

They don't need to exported.

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 131 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1EuA742MQXUTVi1t:-MhQFzky4dVJlBGDMexs:b-km71hc) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L131)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I don't think any of these should be exported.  Can you change them, and use export_test.go to make them available for unit tests?
</blockquote></details>

These should be exported because they are called the connectionlistener package.  Also, this package can be used as general-purpose scamper output parser.  There is no point creating a package that doesn't have any exported functions.

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1ZT_87dyuJqIn2BG:-MhQGeZD8VG7DQOkqlax:bucbhcb) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L165)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

In the alternate parser code we were playing with, I separated out the split and 4 line check.  Since there is duplicate code here, I suggest you pull out code that separates the 4 lines and puts the raw data into 4 fields in an unexported datatype.  Then you can implement these extract functions on that datatype instead of passing in []byte.
</blockquote></details>

I don't quite understand the comment here.  ipcache.Trace() returns []byte, which is passed to the parser.  Is this an issue?

**Comment by SaiedKazemi** [comment]
PTAL

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/118)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[parser/json.go, line 131 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1EuA742MQXUTVi1t:-MhQUi6RD_787iD0_O46:br33s9c) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L131)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

These should be exported because they are called the connectionlistener package.  Also, this package can be used as general-purpose scamper output parser.  There is no point creating a package that doesn't have any exported functions.
</blockquote></details>

Ah - I'm thinking in the wrong context.  That makes sense.
___
*[parser/json.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1ZT_87dyuJqIn2BG:-MhQUpxC2qvvMf1veqhV:b-ep44p2) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L165)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I don't quite understand the comment here.  ipcache.Trace() returns []byte, which is passed to the parser.  Is this an issue?
</blockquote></details>

First, I'd like to point out that this should all be done in the []byte space, without converting to string and back, which causes new allocations.

I was thinking that there could be a first step creating a "type jsonl [][]byte", separating the four lines.  Then these functions could be methods on that jsonl type object.  Everything down to the Unmarshal (in each function) would already be done, in one place, without code duplication.  It would also then be clear that you shouldn't be passing any other []byte into these functions, because the methods will have the correct receiver type.

I don't think these changes will take more than half an hour, IIUC.

Alternatively, since this function is actually parsing EVERYTHING, just create a type that has each of the cycleStart, TracelbLine, and cyclestopLine, parse it all at once, and return the whole object. 

Otherwise, we have code that does stuff and throws it away, then does it again somewhere else, and it is confusing why it is done in two places.  (Not just the split, but also the cyclestart parsing in the current code.)

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1ZT_87dyuJqIn2BG:-MhRTDys1MENkuF3zN8E:b7r7s1p) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L165)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

First, I'd like to point out that this should all be done in the []byte space, without converting to string and back, which causes new allocations.

I was thinking that there could be a first step creating a "type jsonl [][]byte", separating the four lines.  Then these functions could be methods on that jsonl type object.  Everything down to the Unmarshal (in each function) would already be done, in one place, without code duplication.  It would also then be clear that you shouldn't be passing any other []byte into these functions, because the methods will have the correct receiver type.

I don't think these changes will take more than half an hour, IIUC.

Alternatively, since this function is actually parsing EVERYTHING, just create a type that has each of the cycleStart, TracelbLine, and cyclestopLine, parse it all at once, and return the whole object. 

Otherwise, we have code that does stuff and throws it away, then does it again somewhere else, and it is confusing why it is done in two places.  (Not just the split, but also the cyclestart parsing in the current code.)
</blockquote></details>

I see now... thanks for clarifying.  I've changed the code to  parse the output only once without any conversions from bytes to string or vice versa.  PTAL.

**Review by SaiedKazemi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/118)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[parser/json.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1ZT_87dyuJqIn2BG:-MhRVH04EY0tMAuM9zE9:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L165)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I see now... thanks for clarifying.  I've changed the code to  parse the output only once without any conversions from bytes to string or vice versa.  PTAL.
</blockquote></details>

Done.

**Review by SaiedKazemi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/118)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[parser/json.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1ZT_87dyuJqIn2BG:-MhRVXDeAp73IIS1ljrn:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L165)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by gfr10598 — APPROVED** [review]
:lgtm:  with one suggestion.

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-:-MhU3PGWB4M2PFfcT2KV:b1vxtwn)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[connectionlistener/connectionlistener.go, line 48 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhU2xZmB-VWsCnlo2lk:-MhU2xZmB-VWsCnlo2ll:bim829z) ([raw file](https://github.com/m-lab/traceroute-caller/blob/b20000da6c507e5522cf0ccc9a3d057f3b2805cd/connectionlistener/connectionlistener.go#L48)):*
> ```Go
> 
> 	if ok {
> 		go func() {
> ```

Please add a comment here explaining that it is spawning concurrent handling of the entire tracing, postprocessing and file writing.  The cache.Trace name isn't very informative.
___
*[parser/json.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1ZT_87dyuJqIn2BG:-MhU2I8d0niWeGnmwqcX:b-kb5mpk) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L165)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Excellent!  Thanks!

**Comment by SaiedKazemi** [comment]
___
*[parser/json.go, line 165 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhQ1ZT_87dyuJqIn2BG:-MhUNm7751xjptXZ9H54:b-rcidw4) ([raw file](https://github.com/m-lab/traceroute-caller/blob/06949e199509c707bb84f37d2db34f4d74cae18f/parser/json.go#L165)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Excellent!  Thanks!
</blockquote></details>

Ack'ed.

**Comment by SaiedKazemi** [comment]
Thanks.

**Comment by SaiedKazemi** [comment]
___
*[connectionlistener/connectionlistener.go, line 48 at r3](https://reviewable.io/reviews/m-lab/traceroute-caller/118#-MhU2xZmB-VWsCnlo2lk:-MhUNk5oEb5y3OzB6AV2:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/b20000da6c507e5522cf0ccc9a3d057f3b2805cd/connectionlistener/connectionlistener.go#L48)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add a comment here explaining that it is spawning concurrent handling of the entire tracing, postprocessing and file writing.  The cache.Trace name isn't very informative.
</blockquote></details>

Done.

**Pull request merged**
