### PR TITLE
Add package unit testing

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit adds package unit testing to traceroute-caller after
its recent refactor.  Code coverage is as follows:

    traceroute-caller	88.9%
    hopannotation	93.6%
    ipcache	       100.0%
    parser	       100.0%
    tracer	       100.0%
    triggertrace	96.3%

Only 8 lines from the entire traceroute source code where it's
almost impossible to force a failure are not covered.

Changes were tested locally:

    go test -race ./...

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/128)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
Thank you, @saiedkazemi :lgtm:

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-:-Mnl5aKf-T9w_C8zKNgf:b-i32p2b)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[caller.go, line 42 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-MnXJiH90bYOyO10OaJq:-MnXJiH90bYOyO10OaJr:bfr06y) ([raw file](https://github.com/m-lab/traceroute-caller/blob/f0ddf6211f7e3d25054d8638528bb67dd850b262/caller.go#L42)):*
> ```Go
> 	logFatalf      = log.Fatalf
> 	errEventSocket = "tcpinfo.eventsocket value was empty"
> 	errNewHandler  = "failed to create handler"
> ```

I still find it peculiar to name string variables `errFoo` when they are not Error types.

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/128)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[caller_test.go, line 74 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-Mnlwh310rss_GHeR7j8:-Mnlwh310rss_GHeR7j9:b-61f70f) ([raw file](https://github.com/m-lab/traceroute-caller/blob/f0ddf6211f7e3d25054d8638528bb67dd850b262/caller_test.go#L74)):*
> ```Go
> 	case <-srvDone:
> 	case <-time.After(1 * time.Second):
> 		t.Errorf("eventsocket server goroutine still running")
> ```

When I see sleeps in tests, I worry that it's only a matter of time before a race is successful.

I ran `while go test -v -count=1 ./ ; do sleep .1 ; done` until it failed with the error below.

```
    caller_test.go:74: eventsocket server goroutine still running
--- FAIL: TestMainFunc (2.98s)
```

Is there a way to make the server setup and shutdown deterministic? (doesn't have to be this PR, but I imagine this is something you care about -- and maybe it's not practically possible -- but we also don't want the test to fail unless there's a real problem -- so perhaps increasing the constant delay (which doesn't feel satisfying, but might get the job done).

**Comment by SaiedKazemi** [comment]
___
*[caller.go, line 42 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-MnXJiH90bYOyO10OaJq:-MpgCUHs5wZNS8y9dzAt:b-poc52n) ([raw file](https://github.com/m-lab/traceroute-caller/blob/f0ddf6211f7e3d25054d8638528bb67dd850b262/caller.go#L42)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I still find it peculiar to name string variables `errFoo` when they are not Error types.
</blockquote></details>

Because these are error messages, they are prefixed by "err".  I don't think all variable names that start with "err" should only be of type "error".

Anyway, I changed them to type error to avoid any potential confusion.

**Comment by SaiedKazemi** [comment]
___
*[caller_test.go, line 74 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-Mnlwh310rss_GHeR7j8:-MpgD3gm3F5UUJJ7XSlq:bhxm1z1) ([raw file](https://github.com/m-lab/traceroute-caller/blob/f0ddf6211f7e3d25054d8638528bb67dd850b262/caller_test.go#L74)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

When I see sleeps in tests, I worry that it's only a matter of time before a race is successful.

I ran `while go test -v -count=1 ./ ; do sleep .1 ; done` until it failed with the error below.

```
    caller_test.go:74: eventsocket server goroutine still running
--- FAIL: TestMainFunc (2.98s)
```

Is there a way to make the server setup and shutdown deterministic? (doesn't have to be this PR, but I imagine this is something you care about -- and maybe it's not practically possible -- but we also don't want the test to fail unless there's a real problem -- so perhaps increasing the constant delay (which doesn't feel satisfying, but might get the job done).
</blockquote></details>

I agree that it's not desirable to have sleeps but in this particular case I don't think we have much choice because Serve() does not return unless its context is cancelled.

The test cancels the context after one second and we now wait two seconds for Serve() to return.  This should prevent the error that you reported earlier.

**Comment by SaiedKazemi** [comment]
Thanks a lot for your review @stephen-soltesz.  Because I made some minor changes based on your review comments, could you please take another look?

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- but, I wasn't sure where/how the staticcheck.conf is used..

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-:-MpgPvHG0Hr47QW4gNAa:b375ux6)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[ipcache/staticcheck.conf, line 1 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-MpgPacU6jm47nxJUklq:-MpgPacU6jm47nxJUklr:b-xtpi8y) ([raw file](https://github.com/m-lab/traceroute-caller/blob/05e75121474075bf871debcc3a3deb9b8283216f/ipcache/staticcheck.conf#L1)):*
> ```
> checks = ["all", "-SA1012"]
> ```

What uses this file?

**Comment by SaiedKazemi** [comment]
___
*[ipcache/staticcheck.conf, line 1 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-MpgPacU6jm47nxJUklq:-MpgWgr87p3u8niQdbD6:b4iu5zi) ([raw file](https://github.com/m-lab/traceroute-caller/blob/05e75121474075bf871debcc3a3deb9b8283216f/ipcache/staticcheck.conf#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What uses this file?
</blockquote></details>

As part of making sure my changes are good, I run `staticcheck`.  This particular file in the `ipcache` directory is meant to prevent `staticcheck` from complaining that nil is not a valid context value.

$ cd ipcache
$ mv staticcheck.conf staticcheck.conf.KEEP
$ staticcheck .
ipcache_test.go:42:27: do not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use (SA1012)
$ sed -n '40,45p' ipcache_test.go 
func TestNew(t *testing.T) {
        // nolint:staticcheck
        if _, err := ipcache.New(nil, nil, ipcache.Config{}); err == nil {
                t.Error("FetchTrace() = nil, want error")
        }
        if _, err := ipcache.New(context.TODO(), &fakeTracer{}, ipcache.Config{}); err == nil {
$ mv staticcheck.conf.KEEP staticcheck.conf      
$ staticcheck .
$ echo $?
0

**Comment by SaiedKazemi** [comment]
Thanks again.  Please see my explanation of `staticcheck.conf` in the other comment.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/128)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[ipcache/staticcheck.conf, line 1 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-MpgPacU6jm47nxJUklq:-MpgYJ_6C4vuRuExpxm3:b9gjepr) ([raw file](https://github.com/m-lab/traceroute-caller/blob/05e75121474075bf871debcc3a3deb9b8283216f/ipcache/staticcheck.conf#L1)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

As part of making sure my changes are good, I run `staticcheck`.  This particular file in the `ipcache` directory is meant to prevent `staticcheck` from complaining that nil is not a valid context value.

$ cd ipcache
$ mv staticcheck.conf staticcheck.conf.KEEP
$ staticcheck .
ipcache_test.go:42:27: do not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use (SA1012)
$ sed -n '40,45p' ipcache_test.go 
func TestNew(t *testing.T) {
        // nolint:staticcheck
        if _, err := ipcache.New(nil, nil, ipcache.Config{}); err == nil {
                t.Error("FetchTrace() = nil, want error")
        }
        if _, err := ipcache.New(context.TODO(), &fakeTracer{}, ipcache.Config{}); err == nil {
$ mv staticcheck.conf.KEEP staticcheck.conf      
$ staticcheck .
$ echo $?
0

</blockquote></details>

Should running staticcheck be added to the standard CI steps for traceroute-caller? That way we can guarantee it's always executed.

**Comment by SaiedKazemi** [comment]
___
*[ipcache/staticcheck.conf, line 1 at r2](https://reviewable.io/reviews/m-lab/traceroute-caller/128#-MpgPacU6jm47nxJUklq:-Mpg_2uVBmsBnRVaeWjh:bru3gm2) ([raw file](https://github.com/m-lab/traceroute-caller/blob/05e75121474075bf871debcc3a3deb9b8283216f/ipcache/staticcheck.conf#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should running staticcheck be added to the standard CI steps for traceroute-caller? That way we can guarantee it's always executed.
</blockquote></details>

Two things come to mind with respect to adding `staticcheck` only to `traceroute-caller` standard CI steps:

1. It's better to have a consistent set of checks across all our Go repos as opposed to running some checks against one repo and other checks against another repo.

2. Installing `staticcheck` for repos running a version of Go earlier than 1.17 is a bit tricky.  Beginning with Go 1.17, it can be installed simply with `go install honnef.co/go/tools/cmd/staticcheck@latest`.  `traceroute-caller` is currently using Go 1.16 and  I am not sure what versions of Go other repos use.

That said, I am in favor or having more code checks and tests in our standard CI steps for all our repos and using the same version of Go.

**Pull request merged**
