### PR TITLE
Pull out common code in trace functions

### PR DESCRIPTION
**Pull request by gfr10598**
This is not a strict refactoring, but is not intended to change behavior in any way.

Passes unit tests.  We should probably also run it in sandbox manually.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/114)

### CODE REVIEW

**Comment by gfr10598** [comment]
I've pushed it manually to sandbox ndt pods.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 83 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/114#-MdZU9GhEVLAJvB8WBlD:-MdZU9GhEVLAJvB8WBlE:bafyoc4) ([raw file](https://github.com/m-lab/traceroute-caller/blob/38a3f9a6f35e2fc762f6348b3d5ab7f968ea2842/tracer/scamper.go#L83)):*
> ```Go
> // called binaries have a much smaller "blast radius".
> func (s *Scamper) Trace(conn connection.Connection, t time.Time) (out []byte, err error) {
> 	// XXX Is this still useful?  Does shx.PipeJob we ever panic?
> ```

shx does not panic, so this recover() should never happen.  But I suggest we change (correct) error/panic/recovery handling in a separate PR.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 180 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/114#-MdZUr0f86O_Lix49xtJ:-MdZUr0f86O_Lix49xtK:bfi8avq) ([raw file](https://github.com/m-lab/traceroute-caller/blob/38a3f9a6f35e2fc762f6348b3d5ab7f968ea2842/tracer/scamper.go#L180)):*
> ```Go
> // connection.
> func (d *ScamperDaemon) Trace(conn connection.Connection, t time.Time) (out []byte, err error) {
> 	// XXX Is this still useful?  Does shx.PipeJob we ever panic?
> ```

See my previous comment.

**Comment by SaiedKazemi** [comment]
___
*[tracer/scamper.go, line 272 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/114#-MdZV53779jDTHdensfB:-MdZV53779jDTHdensfC:b-whg3ho) ([raw file](https://github.com/m-lab/traceroute-caller/blob/38a3f9a6f35e2fc762f6348b3d5ab7f968ea2842/tracer/scamper.go#L272)):*
> ```Go
> 		}
> 		return buff.Bytes(), err
> 	} else {
> ```

Please remove this unnecessary else.

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/114)* status: 0 of 1 approvals obtained (waiting on @gfr10598)

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/114)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[tracer/scamper.go, line 83 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/114#-MdZU9GhEVLAJvB8WBlD:-MdbsQZ6Bgn-u0kDgiQb:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/38a3f9a6f35e2fc762f6348b3d5ab7f968ea2842/tracer/scamper.go#L83)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

shx does not panic, so this recover() should never happen.  But I suggest we change (correct) error/panic/recovery handling in a separate PR.
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 180 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/114#-MdZUr0f86O_Lix49xtJ:-MdbsQ0H-68_oaG7Efrh:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/38a3f9a6f35e2fc762f6348b3d5ab7f968ea2842/tracer/scamper.go#L180)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

See my previous comment.
</blockquote></details>

Done.
___
*[tracer/scamper.go, line 272 at r1](https://reviewable.io/reviews/m-lab/traceroute-caller/114#-MdZV53779jDTHdensfB:-MdbsPHICMtD5-vQQzA4:b-896fix) ([raw file](https://github.com/m-lab/traceroute-caller/blob/38a3f9a6f35e2fc762f6348b3d5ab7f968ea2842/tracer/scamper.go#L272)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Please remove this unnecessary else.
</blockquote></details>

Done.

**Review by gfr10598 — COMMENTED** [review]
FYI, I'm separating out the simple []byte and _test stuff into a separate PR to do first.  #115  

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/114#-:-Mdbshw52_7W37xGmRfV:b-vs1l7b)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/114)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by gfr10598 — COMMENTED** [review]
I found a couple bugs and fixed them.  Also, the previous code (v0.8.4 currently in staging) does have a code path that would write partial results, but only from other errors, not from timeouts).  The refactoring removes that behavior, which I think is what we want for now anyway.

PTAL

> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/114#-:-MdczBJC5ksvj4ICo0Un:b-bt3due)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/traceroute-caller/114)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
